### PR TITLE
meson: Add libucontext to libshared_deps

### LINKED ISSUE #42236: libsystemd/sd-future/fiber fails to compile on musl
### systemd version the issue has been seen with

261-dev

### Used distribution

postmarketOS

### Linux kernel version used

7.0.8

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

systemd should compile

### Unexpected behaviour you saw

build fails with:

```
ninja: job failed: cc  -o test-libudev-static-sym test-libudev-static-sym.p/meson-generated_.._src_test_test-libudev-sym.c.o -Wl,--as-needed -Wl,--no-undefined -pie -fstack-protector -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs -Os -fstack-clash-protection -Wformat -Werror=format-security -g -Wl,-rpath,XXXXXXXXXXXXXXXX libudev.a -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,-z,gcs-report-dynamic=none -Wl,--gc-sections -Wl,--warn-common -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,-z,gcs-report-dynamic=none -Wl,--gc-sections -Wl,--warn-common
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: libudev.a(src_libsystemd_sd-future_fiber.c.o): in function `fiber_init':
/tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:228:(.text+0x7b8): undefined reference to `getcontext'
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: /tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:241:(.text+0x83c): undefined reference to `makecontext'
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: /tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:246:(.text+0x87c): undefined reference to `swapcontext'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce the problem

build systemd on musl-1.2.6

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
bisected to:


commit 8533513aff3cc5bdb03b82ef503489ee8683478e
Author: Daan De Meyer <daan.j.demeyer@gmail.com>
Date:   Wed Nov 12 17:53:47 2025 +0100

    Introduce support for running code in fibers
```

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes #42236

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by craftyguy** [comment]
thanks, fixes compilation for me :D

**Review by yuwata — APPROVED** [review]
