### ISSUE TITLE
systemd fails to compile with gcc 9.1.1

### ISSUE THREAD

**Issue by oaivanov** [systemd/systemd#17008]
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Buildroot 2020.08
 > Compiling on CentOS 7

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
./src/journal/sd-journal.c: In function ‘sd_journal_open_files_fd’:
../src/journal/sd-journal.c:1293:28: error: argument 2 null where non-null expected [-Werror=nonnull]
                         fd = openat(j->toplevel_fd, skip_slash(path), O_RDONLY|O_CLOEXEC|O_NONBLOCK);
                         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/journal/sd-journal.c:1295:28: error: argument 1 null where non-null expected [-Werror=nonnull]
                         fd = open(path, O_RDONLY|O_CLOEXEC|O_NONBLOCK);
                         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Full log attached
[build.txt](https://github.com/systemd/systemd/files/5203221/build.txt)


**Steps to reproduce the problem**
gcc (GCC) 9.1.1 20190605 (Red Hat 9.1.1-2)
from CentOS SCLo RH x86_64 Repo devtoolset-9-gcc-9.1.1-2.6.el7.x86_64

**Comment by keszybz** [comment]
The code is fine, it's a bug in the static analyzer in the compiler. Sorry, there's nothing we can do upstream. You need to work-around this by either ugprading the compiler or doing some local patch or twiddling the compile options.

**Comment by yuwata** [comment]
Yeah, `add_any_file()` has `assert(fd >= 0 || path);`. So, `path` is non-NULL there.

**Comment by oaivanov** [comment]
Thanks, I assumed it was a compiler problem. We'll do work-around or change compiler.
