### PR TITLE
resolve: initialize `r` during OOM

### PR DESCRIPTION
**Pull request by mrc0mmand**
Otherwise we'd use some garbage value in the error path.
```
../src/resolve/resolved-dns-query.c: In function ‘dns_query_accept’: ../src/resolve/resolved-dns-query.c:944:27: error: ‘r’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  944 |         q->answer_errno = -r;
      |                           ^~
cc1: all warnings being treated as errors
```
Follow-up for 9ca133e97a0.

---
This should address the failing Ubuntu CI since https://github.com/systemd/systemd/pull/30513.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by mrc0mmand** [comment]
I wanted to add a CI configuration for this (or, more specifically, tweak an existing one), as according to one of the comments in `meson.build` we support `-Wmaybe-initialized` with `-O0` and `-O2` (and this patch makes the warning go away), but there's a couple of false positives I'm trying to get rid of, and I think gcc is just mocking me here:

```
[543/2418] Compiling C object src/shared/libsystemd-shared-255.a.p/tpm2-util.c.o
In file included from ../src/basic/alloc-util.h:276,
                 from ../src/shared/tpm2-util.c:5:
In function ‘memcpy_safe’,
    inlined from ‘tpm2_calculate_seal_seed’ at ../src/shared/tpm2-util.c:5058:21,
    inlined from ‘tpm2_calculate_seal’ at ../src/shared/tpm2-util.c:5136:13:
../src/basic/memory-util.h:27:16: warning: ‘seed_size’ may be used uninitialized [-Wmaybe-uninitialized]
   27 |         return memcpy(dst, src, n);
      |                ^~~~~~~~~~~~~~~~~~~
../src/shared/tpm2-util.c: In function ‘tpm2_calculate_seal’:
../src/shared/tpm2-util.c:5047:16: note: ‘seed_size’ was declared here
 5047 |         size_t seed_size = 0, encrypted_seed_size = 0; /* Explicit initialization to appease gcc */
      |                ^~~~~~~~~

```

**Review by yuwata — APPROVED** [review]

File: src/libsystemd/sd-journal/journal-file.c [hunk 1]
```diff
@@ -2757,7 +2757,7 @@ static int generic_array_get(
                 Object **ret_object,    /* The found object. */
                 uint64_t *ret_offset) { /* The offset of the found object. */
 
-        uint64_t a, t = 0, k;
+        uint64_t a, t = 0, k = 0;
```
Comment (yuwata) [inline src/libsystemd/sd-journal/journal-file.c]: Could you also add a short comment for the initialization of `k` ?

Comment (mrc0mmand) [reply src/libsystemd/sd-journal/journal-file.c]: Hopefully it's the last one (at least testing this locally on Ubuntu Jammy finally made gcc happy).
