### PR TITLE
Various follow-up: Fix build and EINVAL for _INVALID enum value

### LINKED ISSUE #18639: build failure if building with -Ddns-over-tls=openssl
**systemd version the issue has been seen with**
master 

**Expected behaviour you didn't see**
 clean build

**Unexpected behaviour you saw**
 build fails

**Steps to reproduce the problem**
 build systemd with -Dopenssl=true -Ddns-over-tls=openssl

**Additional program output to the terminal or log subsystem illustrating the issue**

```
In file included from ../../../src/systemd/src/basic/io-util.h:10,
                 from ../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:11:
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c: In function ‘SSL_freep’:
../../../src/systemd/src/basic/macro.h:412:28: error: void value not ignored as it ought to be
  412 |                         *p = func(*p);                          \
      |                            ^
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:16:1: note: in expansion of macro ‘DEFINE_TRIVIAL_CLEANUP_FUNC’
   16 | DEFINE_TRIVIAL_CLEANUP_FUNC(SSL*, SSL_free);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c: In function ‘BIO_freep’:
../../../src/systemd/src/basic/macro.h:412:28: warning: assignment to ‘BIO *’ {aka ‘struct bio_st *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  412 |                         *p = func(*p);                          \
      |                            ^
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:17:1: note: in expansion of macro ‘DEFINE_TRIVIAL_CLEANUP_FUNC’
   17 | DEFINE_TRIVIAL_CLEANUP_FUNC(BIO*, BIO_free);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems to be caused by https://github.com/systemd/systemd/commit/fd421c4adc7406de02e03e2f7ceede2cc6e1d9d4 ,
it looks like resolved-dnstls-openssl.c was not updated.

This patch fixes the issue for me:
```
diff --git a/src/resolve/resolved-dnstls-openssl.c b/src/resolve/resolved-dnstls-openssl.c
index defddb5237..17af90d4cc 100644
--- a/src/resolve/resolved-dnstls-openssl.c
+++ b/src/resolve/resolved-dnstls-openssl.c
@@ -13,8 +13,8 @@
 #include "resolved-dnstls.h"
 #include "resolved-manager.h"

-DEFINE_TRIVIAL_CLEANUP_FUNC(SSL*, SSL_free);
-DEFINE_TRIVIAL_CLEANUP_FUNC(BIO*, BIO_free);
+DEFINE_TRIVIAL_CLEANUP_FUNC_FULL(SSL*, SSL_free, NULL);
+DEFINE_TRIVIAL_CLEANUP_FUNC_FULL(BIO*, BIO_free, NULL);

 static int dnstls_flush_write_buffer(DnsStream *stream) {
         ssize_t ss;
```

However as I have no idea about crypto stuff I'm hesitant to PR this fix.

### PR DESCRIPTION
**Pull request by benjarobin**
Please double check that I did not break compatibility, since this was specified in commit 2d93c20e:
> This does not touch anything exposed in src/systemd. Changing the defines there would be a compatibility break.

Fixes #18639.

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by keszybz** [comment]
> Please double check that I did not break compatibility, since this was specified in commit [2d93c20](https://github.com/systemd/systemd/commit/2d93c20e5f600a9f1e4b617123577acf6ce5faa0):
> 
> > This does not touch anything exposed in src/systemd. Changing the defines there would be a compatibility break.

That commit message is not up to date: the original version of the patch excluded all of src/systemd. Later it was changed because only files that are not actually exported were touched.

**Comment by keszybz** [comment]
LGTM.

It seems we don't have an openssl built in CI. We should fix that. ← @fsumsal ?

File: src/portable/portable.h [hunk 1]
```diff
@@ -31,7 +31,7 @@ typedef enum PortableChangeType {
         PORTABLE_WRITE,
         PORTABLE_MKDIR,
         _PORTABLE_CHANGE_TYPE_MAX,
-        _PORTABLE_CHANGE_TYPE_INVALID = INT_MIN,
+        _PORTABLE_CHANGE_TYPE_INVALID = -EINVAL,
```
Comment (poettering) [inline src/portable/portable.h:34]: uh, hm, so this is problematic conceptually (though not in practice). PotableChangeType can be negative or positive, and we pick a _PORTABLE_CHANGE_TYPE_INVALID value really far away from the valid cases to ensure they don't conflict...

now in practice this doesn't matter, since EINVAL is 22, i.e. they do *not* conflict, but we should probably make this explicit, by mapping all negative values here explicitly, so that the compiler notices any collision

File: src/shared/install.h [hunk 2]
```diff
@@ -31,7 +31,7 @@ enum UnitFileChangeType {
         UNIT_FILE_IS_MASKED,
         UNIT_FILE_IS_DANGLING,
         _UNIT_FILE_CHANGE_TYPE_MAX,
-        _UNIT_FILE_CHANGE_TYPE_INVALID = INT_MIN
+        _UNIT_FILE_CHANGE_TYPE_INVALID = -EINVAL,
```
Comment (poettering) [inline src/shared/install.h:34]: same case here

File: src/portable/portable.h (hunk 1 above)
Comment (poettering) [reply src/portable/portable.h:34]: sorry, actually it's more complicated... where we store PortableChangeType we can also store any errno actually, and suddenly it's even more messy

Comment (benjarobin) [reply src/portable/portable.h:34]: I did not fully understand your fist message.
But, that is why, I did create separate commit for each change. I was not sure about all the changes, and the MR was merged very quickly.
Well we can just revert it, and add a comment about it.

Comment (poettering) [reply src/portable/portable.h:34]: na, no need to revert. the change is good, but our enum use before, was a bit let's say… adventurous. I am working on a fix.
