### PR TITLE
Metrics: Refactor to drop usage of strv

### PR DESCRIPTION
**Pull request by YapingLi04**
This addresses @daandemeyer's feedback on #39202

### CODE REVIEW

File: src/shared/metrics.h [hunk 1]
```diff
@@ -2,8 +2,7 @@
 #pragma once
 
 #include "sd-varlink.h"
```
Comment (daandemeyer) [inline src/shared/metrics.h]: Please drop this include

Comment (YapingLi04) [reply src/shared/metrics.h]: If I drop this include, the build fails with this error. Did I miss something?

```
In file included from ../src/core/varlink-metrics.c:5:
../src/shared/metrics.h:35:17: error: unknown type name ‘sd_varlink_method_t’; did you mean ‘sd_varlink_method_flags_t’?
   35 |                 sd_varlink_method_t vl_method_list_cb,
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 sd_varlink_method_flags_t
../src/shared/metrics.h:36:17: error: unknown type name ‘sd_varlink_method_t’; did you mean ‘sd_varlink_method_flags_t’?
   36 |                 sd_varlink_method_t vl_method_describe_cb,
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 sd_varlink_method_flags_t
```

Comment (YHNdnzj) [reply src/shared/metrics.h]: please add a forward decl to sd-forward.h

File: src/shared/metrics.c [hunk 2]
```diff
@@ -217,21 +178,27 @@ static int metric_build_send(MetricFamilyContext *context, const char *object, s
...
+        if (fields) {
+                if (!sd_json_variant_is_object(fields))
+                        return log_debug_errno(SYNTHETIC_ERRNO(EINVAL), "Fields must be a JSON object");
+
+                const char *k;
+                sd_json_variant *e;
+                JSON_VARIANT_OBJECT_FOREACH(k, e, fields)
+                        if (!sd_json_variant_is_string(e))
+                                return log_debug_errno(SYNTHETIC_ERRNO(EINVAL),
+                                                       "Field '%s' value is not a string", k);
```
Comment (keszybz) [inline src/shared/metrics.c]: This is internal code. For things that we generate ourselves, returning an negative error generally is not useful. Instead, it should be a hard assert. And maybe it should be moved to the point of generation.

**Comment by keszybz** [comment]
Oh, and please stop using square brackets in the prefix. We use "prefix: ".

File: src/shared/metrics.h (hunk 1 above)
Comment (YapingLi04) [reply src/shared/metrics.h]: thanks. added

File: src/shared/metrics.c (hunk 2 above)
Comment (YapingLi04) [reply src/shared/metrics.c]: thanks. Updated to use `assert`. The points of generation for `fields` are scattered and a couple of functions calls above. It's probably cleaner to keep the check in this function.

**Comment by YapingLi04** [comment]
fixed build error

**Comment by bluca** [comment]
```
2026-02-10T18:49:37.9117032Z ../src/shared/metrics.c:185:34: error: variable ‘e’ set but not used [-Werror=unused-but-set-variable]
2026-02-10T18:49:37.9117831Z   185 |                 sd_json_variant *e;
```

**Comment by YapingLi04** [comment]
fixed unused variable error

**Comment by keszybz** [comment]
This patch seems fine. There was a problem introduced in 0ec663a41fc49a3e4ec592c4e0037f4bc7e8f6fc, I'll submit a patch.
