### PR TITLE
Add AF_VSOCK socket activation support

### PR DESCRIPTION
**Pull request by stefanha**
The AF_VSOCK address family facilitates guest<->host communication under VMware and KVM (virtio-vsock since Linux 4.8).

These patches add the address family and enable socket activation.  The QEMU guest agent has been extended to support systemd socket activation.  Other guest/host services can also take advantage of this feature.

AF_VSOCK addressing is a <u32 cid, u32 port> pair.  The ListenStream=vsock:<cid>:<port> syntax was chosen since it does not conflict with IPv4/IPV6 or other supported address syntax.

### CODE REVIEW

**Comment by martinpitt** [comment]
This fails to build in Semaphore (Ubuntu 14.04) and the Fedora test:
```
In file included from ../src/shared/firewall-util.c:46:0:
../src/basic/socket-util.h:31:30: fatal error: linux/vm_sockets.h: No such file or directory
 #include <linux/vm_sockets.h>
```
So apparently this include was only added to later kernels, and thus this needs to be conditionalized and tested in `configure.ac`.

File: src/basic/socket-util.c [hunk 1]
```diff
@@ -113,6 +113,30 @@ int socket_address_parse(SocketAddress *a, const char *s) {
...
+                e = strchr(cid_start, ':');
+                if (!e)
+                        return -EINVAL;
+
+                r = safe_atou(e+1, &u);
+                if (r < 0)
+                        return r;
+
+                n = strndupa(cid_start, e - cid_start);
+                if (*n != '\0') {
```
Comment (poettering) [inline src/basic/socket-util.c]: maybe use isempty() here? might make this a bit more readable...

File: man/systemd.socket.xml [hunk 2]
```diff
@@ -216,6 +216,11 @@
         <varname>BindIPv6Only=</varname> setting (see below).
         </para>
 
+        <para>If the address string is a string in the format
+        vsock:x:y, it is read as CID x on a port y address in the
```
Comment (poettering) [inline man/systemd.socket.xml]: the `vsock:x:y` should be enclosed in `<literal></literal>` I figure...

Hmm, what's a CID precisely? I think it would be nice to briefly explain that in brackets or so.

`x` and `y` should be enclosed in `<literal></literal>` too I figure.

File: man/systemd.socket.xml [hunk 3]
```diff
@@ -216,6 +216,11 @@
...
+        <constant>AF_VSOCK</constant> family.  Specifying the CID is
+        optional so vsock::y is accepted as well.</para>
```
Comment (poettering) [inline man/systemd.socket.xml]: Again, `<literal></literal>`...

the english sounds a bit off here. Maybe just say "Specifying the CID is optional, and may be set to the empty string in that case" or so?

**Comment by poettering** [comment]
Hmm, given that the needed definitions are relatively minor I think it would make sense to add them properly `#ifdef`fed to `missing.h`, so that we can compile AF_VSOCK also on older libc/kernel combinations.

**Comment by stefanha** [comment]
Changes in v2:
 * Fix Ubuntu 14.04 build by adding struct sockaddr_vm and VMADDR_CID_ANY to missing.h
 * Use isempty() in socket-util.c
 * Use <literal> in systemd.socket.xml
 * Explain CID concept in systemd.socket.xml
 * Reword optional CID parameter in systemd.socket.xml

**Comment by stefanha** [comment]
There seems to be a failure with v2, I'll investigate them.

**Comment by stefanha** [comment]
v3:
 * Fixed if (isempty(n)) { ...use n... } inverted logic bug
 * Add AF_VSOCK definition for CentOS build
