### PR TITLE
seccomp: add support for riscv64

### PR DESCRIPTION
**Pull request by mbiebl**
This patch adds seccomp support to the riscv64 architecture. seccomp
support is available in the riscv64 kernel since version 5.5, and it
has just been added to the libseccomp library.

riscv64 uses generic syscalls like aarch64, so I used that architecture
as a reference to find which code has to be modified.

With this patch, the testsuite passes successfully, including the
test-seccomp test. The system boots and works fine with kernel 5.4 (i.e.
without seccomp support) and kernel 5.5 (i.e. with seccomp support). I
have also verified that the "SystemCallFilter=~socket" option prevents a
service to use the ping utility when running on kernel 5.5.

Patch courtesy of Aurelien Jarno <aurelien@aurel32.net>

### CODE REVIEW

**Comment by mbiebl** [comment]
https://github.com/seccomp/libseccomp/commit/5b03588343426c85f282f311d4247e6b17cfbacb

**Comment by keszybz** [comment]
semaphoreci:
```
../src/basic/macro.h:494:73: note: in definition of macro ‘IN_SET’
                 static const long double __assert_in_set[] _unused_ = { __VA_ARGS__ }; \
                                                                         ^~~~~~~~~~~
../src/shared/seccomp-util.c: In function ‘seccomp_restrict_address_families’:
../src/shared/seccomp-util.c:1346:22: error: ‘SCMP_ARCH_RISCV64’ undeclared (first use in this function); did you mean ‘SCMP_ARCH_PARISC64’?
                 case SCMP_ARCH_RISCV64:
                      ^~~~~~~~~~~~~~~~~
                      SCMP_ARCH_PARISC64
../src/shared/seccomp-util.c: In function ‘seccomp_memory_deny_write_execute’:
../src/shared/seccomp-util.c:1630:22: error: ‘SCMP_ARCH_RISCV64’ undeclared (first use in this function); did you mean ‘SCMP_ARCH_PARISC64’?
                 case SCMP_ARCH_RISCV64:
                      ^~~~~~~~~~~~~~~~~
                      SCMP_ARCH_PARISC64
```
azure and centos ci fail similarly.

**Comment by mbiebl** [comment]
This needs the above commit in libseccomp. Afaics there is no official release yet of libseccomp with that commit though (in Debian it was cherry-picked). 
Once that happens, I assume the min version in meson.build would have to be bumped as well.

**Comment by keszybz** [comment]
If this is too be merged anytime soon, it'll have to be amended to not break with older libseccomp and kernels.

**Comment by mbiebl** [comment]
@aurel32 ^

**Comment by mbiebl** [comment]
Let's postpone this until we have a libseccomp upstream release support riscv64. I hope it's ok to leave this PR open.

**Comment by poettering** [comment]
so an uptsream libseccomp version has long been released. Either way this patch requires some ifdeffery so that we don't use the definition if it isn't there. We have similar ifdeffery for PARISC, it's not difficult to add to RISCV too.

Dropping the "postponed" flag, since it's not really about that anymore. The patch just needs some ifdeffery now.

**Comment by aurel32** [comment]
It appears that support for PARIS is limited to `src/nspawn/nspawn-oci.c`. I guess Ie should use the same `#ifdef` strategy in the other parts of the code.

**Comment by aurel32** [comment]
I have just done that there: https://github.com/aurel32/systemd/commit/f81ee95992ec068bbfac4afc7f5343f6d7393a87

As I am not the creator of this PR, not sure how to continue further. Should I just create a new one?

**Comment by keszybz** [comment]
Yes, please create a new PR.

**Comment by aurel32** [comment]
> Yes, please create a new PR.

Done, it's PR #16807. Please close this one.
