### ISSUE TITLE
systemd-236 fails to build without libgcrypt being present

### ISSUE THREAD

**Issue by tgurr** [systemd/systemd#7845]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Exherbo

### In case of bug report: Expected behaviour you didn't see

> Compile successfully

### In case of bug report: Unexpected behaviour you saw

> Error during compilation

```
x86_64-pc-linux-gnu-cc  -Itest-dnssec@exe -I. -I../systemd-236 -I../systemd-236/ -Isrc/libsystemd-network -I../systemd-236/src/libsystemd-network -I../systemd-236/src/libsystemd/sd-network -I../systemd-236/src/libsystemd/sd-netlink -I../systemd-236/src/libsystemd/sd-id128 -I../systemd-236/src/libsystemd/sd-hwdb -I../systemd-236/src/libsystemd/sd-device -I../systemd-236/src/libsystemd/sd-bus -Isrc/core -I../systemd-236/src/core -Isrc/libudev -I../systemd-236/src/libudev -Isrc/udev -I../systemd-236/src/udev -Isrc/login -I../systemd-236/src/login -Isrc/timesync -I../systemd-236/src/timesync -Isrc/resolve -I../systemd-236/src/resolve -Isrc/journal -I../systemd-236/src/journal -Isrc/systemd -I../systemd-236/src/systemd -Isrc/shared -I../systemd-236/src/shared -Isrc/basic -I../systemd-236/src/basic -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong -fPIE --param=ssp-buffer-size=4 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -include config.h -march=native -O2 -march=native -O2 -MMD -MQ 'test-dnssec@exe/src_resolve_test-dnssec.c.o' -MF 'test-dnssec@exe/src_resolve_test-dnssec.c.o.d' -o 'test-dnssec@exe/src_resolve_test-dnssec.c.o' -c ../systemd-236/src/resolve/test-dnssec.c
../systemd-236/src/resolve/test-dnssec.c:22:20: fatal error: gcrypt.h: No such file or directory
 #include <gcrypt.h>
                    ^
compilation terminated.
```

### In case of bug report: Steps to reproduce the problem

> Uninstall libgcrypt from your system and try to build systemd-236 passing `-Dgcrypt=false` to meson.

The problem looks like it has been introduced with https://github.com/systemd/systemd/commit/cb9eeb062c323391fcd98da0c30e844fa5162e90.

**Comment by poettering** [comment]
any chance you can prep a fix?

**Comment by Werkov** [comment]
Actually, I had this buffered when dealing with such builds as well -- this minor ifdef fixed that for me.
