### PR TITLE
efi: use stub for cache_efi_options_variable if !ENABLE_EFI

### PR DESCRIPTION
**Pull request by bluca**
../src/core/main.c: In function 'main':
../src/core/main.c:2637:32: error: implicit declaration of function 'cache_efi_options_variable'; did you mean 'systemd_efi_options_variable'? [-Werror=implicit-function-declaration]
                         (void) cache_efi_options_variable();
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                systemd_efi_options_variable

Build failure introduced by https://github.com/systemd/systemd/pull/16139

### CODE REVIEW

File: src/basic/efivars.h [hunk 1]
```diff
@@ -69,6 +69,10 @@ static inline bool is_efi_secure_boot_setup_mode(void) {
         return false;
 }
 
+static inline int cache_efi_options_variable(void) {
+        return -ENOTSUP;
```
Comment (poettering) [inline src/basic/efivars.h]: ENOTSUP is a a weird Linux alias for EOPNOTSUPP. We genreally use the latter, see for example a few lines up. Can you use EOPNOTSUPP here too?

(it's actually even weirder, ENOTSUP in the kernel is different from EOPNOTSUPP, only in userspace it's the same, and the kernel's internal ENOTSUP is converted to EOPNOTSUPP before things are handed to userspace. All in all one never wants to use ENOTSUP)

Comment (bluca) [reply src/basic/efivars.h]: Sure thing, fixed
