### PR TITLE
test: run systemd-dissect and systemd-run with log level debug in TEST-50-DISSECT

### PR DESCRIPTION
**Pull request by bluca**
The test failed once in https://github.com/systemd/systemd/pull/16525 with only:

> testsuite-50.sh[649]: Failed to acquire image metadata: Protocol error

systemd-dissect is failing to analyze the GPT image at:

https://github.com/systemd/systemd/blob/d7d717b/test/units/testsuite-50.sh#L98

dissected_image_acquire_metadata() failed:

https://github.com/systemd/systemd/blob/d7d717b/src/shared/dissect-image.c#L1568

Run the commands with log level debug so that we can see more information

### CODE REVIEW

**Comment by keszybz** [comment]
travis fails with `/build/build/../src/timedate/timedatectl.c:482: undefined reference to `__exp2_finite'`.
```console
$ clang  -o timedatectl 'timedatectl@exe/src_timedate_timedatectl.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-z,now -fstack-protector -Wl,--start-group src/shared/libsystemd-shared-246.so -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/src/shared' -Wl,-rpath-link,/build/build/src/shared
/usr/bin/ld: timedatectl@exe/src_timedate_timedatectl.c.o: in function `print_ntp_status_info':
/build/build/../src/timedate/timedatectl.c:482: undefined reference to `__exp2_finite'
```

**Comment by bluca** [comment]
Rebased to pick up https://github.com/systemd/systemd/pull/16527 and do another round of tests as a bonus, so maybe we get lucky and see the failure again

**Comment by bluca** [comment]
bionic-arm64 unrelated, fails in the test-path unit test with some permission denied errors

**Comment by bluca** [comment]
While doing development on the MountImages feature, the test failed once (among many many runs):

```
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: + /usr/lib/systemd/systemd-dissect /tmp/tmp.l7lurT/minimal.raw
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[647]: + grep -q -F MARKER=1
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: Waiting for device (parent + 0 partitions) to appear...
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: Successfully forked off '(sd-dissect)' as PID 649.
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[649]: Mounting squashfs on /tmp/dissect-H2AtE7 (MS_RDONLY|MS_NODEV "")...
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[649]: Failed to mount /dev/block/7:0 (type squashfs) on /tmp/dissect-H2AtE7 (MS_RDONLY|MS_NODEV ""): No such file or directory
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[649]: Failed to mount dissected image: No such file or directory
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: Failed to read /etc/hostname: No such file or directory
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: /etc/machine-id file is empty.
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: (sd-dissect) failed with exit status 1.
Jul 21 14:15:37 systemd-testsuite testsuite-50.sh[646]: Failed to acquire image metadata: Protocol error
Jul 21 14:15:37 systemd-testsuite kernel: /dev/block/7:0: Can't open blockdev
```

That kernel message is suspicious?

**Comment by bluca** [comment]
The source img is used before in the same test, so the file is unlikely to be absent/corrupted. The destination directory is created beforehand on the fly, so it must exist, or it would fail with a different error.
