### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by mikken** [systemd/systemd#14928]
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Gentoo

This is the error during build:
```
../systemd-245-rc1/src/home/homed-manager.c: In function ‘manager_generate_key_pair’:
../systemd-245-rc1/src/home/homed-manager.c:1292:35: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA1’?
 1292 |         ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_ED25519, NULL);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   EVP_PKEY_DSA1
../systemd-245-rc1/src/home/homed-manager.c:1292:35: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.
```

`evp.h` in current LibreSSL 3.0.2 does not have this define (`EVP_PKEY_ED25519`).

**Comment by zdzichu** [comment]
Why not fix LibreSSL by adding such key types?

**Comment by mikken** [comment]
I'll check with them in the mailing list.

**Comment by poettering** [comment]
Ed25519 is not particularly exotic, in particular not in the OpenBSD world (signify uses it) where LibreSSL comes from... THey really should add that, and we cannot work around it really, and shouldn't.

Sorry, but this is a feature request to make to the LibreSSL people, not us. Sorry!

**Comment by mikken** [comment]
It's okay, I asked in LibreSSL mailing list, they plan to implement this later.

**Comment by mikken** [comment]
Note: with current LibreSSL 3.1.1 this is fixed.

**Comment by ffontaine** [comment]
systemd 250.4 is still failing to build with libressl 3.4.3:

```
../src/home/homed-manager.c: In function ‘manager_generate_key_pair’:
../src/home/homed-manager.c:1393:35: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA1’?
 1393 |         ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_ED25519, NULL);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   EVP_PKEY_DSA1
```

Moreover, I wasn't able to find any mention of `EVP_PKEY_ED25519` in https://github.com/libressl-portable/portable or https://github.com/libressl-portable/openbsd.

Should I disable systemd with libressl on buildroot side?

Full build log: http://autobuild.buildroot.org/results/47f/47f31b36f123c4be4661f4fde2d1f7385c5d0ed5/build-end.log

**Comment by mrc0mmand** [comment]
It looks like ED25519 stuff is not yet in libressl judging by https://github.com/libressl-portable/portable/issues/393? I guess pinging the libressl folks about this should help, there's not much we can do anyway.

> Should I disable systemd with libressl on buildroot side?

Ideally we should keep it, but there's no point in having a constantly failing job wasting resources if this doesn't get addressed.
