### ISSUE TITLE
../src/login/logind-session-device.c:11:10: fatal error: drm/drm.h: No such file or directory

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11075]
Building git master (v239-3180-ga81921e47) results in

```
FAILED: src/login/src@login@@logind-core@sta/logind-session-device.c.o 
cc -Isrc/login/src@login@@logind-core@sta -Isrc/login -I../src/login -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -ffunction-sections -fdata-sections -Werror=shadow -include config.h -g -O2 -fdebug-prefix-map=/home/michael/debian/trunk-ci/systemd-239+upstream20181206=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC  -MD -MQ 'src/login/src@login@@logind-core@sta/logind-session-device.c.o' -MF 'src/login/src@login@@logind-core@sta/logind-session-device.c.o.d' -o 'src/login/src@login@@logind-core@sta/logind-session-device.c.o' -c ../src/login/logind-session-device.c
../src/login/logind-session-device.c:11:10: fatal error: drm/drm.h: No such file or directory
 #include <drm/drm.h>
          ^~~~~~~~~~~
compilation terminated.
```
I do have the linux kernel headers installed
```
$ ls -la /usr/src/linux-headers-4.18.0-3-common/include/uapi/drm/drm.h
-rw-r--r-- 1 root root 31064 Nov 21 09:22 /usr/src/linux-headers-4.18.0-3-common/include/uapi/drm/drm.h
```

**Comment by mbiebl** [comment]
I guess this regression was introduced by dab28f09051445fe370466e767e31652e0804a0f

**Comment by mbiebl** [comment]
$ apt-file search /usr/include/drm/drm.h

returns nothing here, either.

**Comment by yuwata** [comment]
Hmm. All CIs in #11063 were green...

**Comment by yuwata** [comment]
So, why the other kernel headers can be found?

**Comment by yuwata** [comment]
Or, why Ubuntu CIs can find drm/drm.h?

**Comment by mbiebl** [comment]
Debian
```
# apt-file search /usr/include/drm/drm.h
<empty>
```
Ubuntu
```
# apt-file search /usr/include/drm/drm.h
linux-libc-dev: /usr/include/drm/drm.h
```

**Comment by evverx** [comment]
> All CIs in #11063 were green...

Let's make Travis red. @mbiebl I've just opened https://github.com/systemd/systemd/pull/11080 where I modified the script used to build `systemd` on Fedora so that it can be used on Debian. Would you be interesting in maintaining it?

**Comment by mbiebl** [comment]
@evverx nice \o/

**Comment by evverx** [comment]
And now it's red: https://travis-ci.org/systemd/systemd/jobs/464845173 :-)

**Comment by mbiebl** [comment]
@yuwata fwiw, I don't know why the Ubuntu kernel-headers package ships drm/drm.h, but Debians' does not. I do notice there is a libdrm-dev package in Debian which provides ```/usr/include/libdrm/drm.h```
Maybe there is some duplication going on

**Comment by keszybz** [comment]
Maybe just revert https://github.com/systemd/systemd/commit/dab28f09051445fe370466e767e31652e0804a0f? I doesn't seem to gain us much, so it's probably not worth the time to figure this out.

**Comment by yuwata** [comment]
Yeah, it seems so. I will revert the commit soon.

**Comment by yuwata** [comment]
#11081. The same commit is also pushed to #11080. I hope now the debian CI passes.
