### PR TITLE
src/shared/loop-util.c: fix build with kernel < 4.14

### PR DESCRIPTION
**Pull request by rmelotte**
Builds with kernels headers < 4.14 fail with:

../src/shared/loop-util.c: In function ‘loop_configure_fallback’: ../src/shared/loop-util.c:237:31: error: ‘LOOP_SET_BLOCK_SIZE’ undeclared (first use in this function); did you mean ‘LOOP_SET_DIRECT_IO’?
                 if (ioctl(fd, LOOP_SET_BLOCK_SIZE, (unsigned long) c->block_size) < 0)
                               ^~~~~~~~~~~~~~~~~~~
                               LOOP_SET_DIRECT_IO

Fixes: https://github.com/systemd/systemd/issues/33341

### CODE REVIEW

File: src/shared/loop-util.c [hunk 1]
```diff
@@ -36,6 +36,10 @@
 #include "string-util.h"
 #include "tmpfile-util.h"
 
+#ifndef LOOP_SET_BLOCK_SIZE
+#define LOOP_SET_BLOCK_SIZE 0x4C09
```
Comment (YHNdnzj) [inline src/shared/loop-util.c]: Please add this to missing_loop.h instead

**Review by YHNdnzj — CHANGES_REQUESTED** [review]

File: src/shared/loop-util.c (hunk 1 above)
Comment (rmelotte) [reply src/shared/loop-util.c]: Right... Thanks for pointing it out!

**Review by bluca — APPROVED** [review]
