### ISSUE TITLE
Build failure when libfido2 enabled but cryptsetup disabled 

### ISSUE THREAD

**Issue by wylfen** [systemd/systemd#27374]
### systemd version the issue has been seen with

253

### Used distribution

Gentoo

### Linux kernel version used

6.1.25-gentoo

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

I can build systemd using automatic configuration detection on a system that has `libfido2` but not `libcryptsetup`.

### Unexpected behaviour you saw

The build fails with `../src/shared/cryptsetup-fido2.c:153:57: error: ‘CRYPT_LUKS2’ undeclared (first use in this function)`.

Bisect reports 0a8e026e825dda142a8f1552a4b45815cbfd0b48 as first bad commit.

### Steps to reproduce the problem

1. Have a system with `libfido2` but no `libcryptsetup`.
2. `./configure`
3. `make`

Alternatively, to force failure:

1. `meson setup -Dlibfido2=true -Dlibcryptsetup=false build`
2. `ninja -C build`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
../src/shared/cryptsetup-fido2.c: In function ‘acquire_fido2_key_auto’:
../src/shared/cryptsetup-fido2.c:153:37: error: implicit declaration of function ‘sym_crypt_token_max’ [-Werror=implicit-function-declaration]
  153 |         for (int token = 0; token < sym_crypt_token_max(CRYPT_LUKS2); token ++) {
      |                                     ^~~~~~~~~~~~~~~~~~~
../src/shared/cryptsetup-fido2.c:153:37: warning: nested extern declaration of ‘sym_crypt_token_max’ [-Wnested-externs]
../src/shared/cryptsetup-fido2.c:153:57: error: ‘CRYPT_LUKS2’ undeclared (first use in this function)
  153 |         for (int token = 0; token < sym_crypt_token_max(CRYPT_LUKS2); token ++) {
      |                                                         ^~~~~~~~~~~
../src/shared/cryptsetup-fido2.c:153:57: note: each undeclared identifier is reported only once for each function it appears in
../src/shared/cryptsetup-fido2.c:161:21: error: implicit declaration of function ‘cryptsetup_get_token_as_json’ [-Werror=implicit-function-declaration]
  161 |                 r = cryptsetup_get_token_as_json(cd, token, "systemd-fido2", &v);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/cryptsetup-fido2.c:161:21: warning: nested extern declaration of ‘cryptsetup_get_token_as_json’ [-Wnested-externs]
```

**Comment by poettering** [comment]
Uh. This sounds like a relatively nonsensical combination of switches (since the libfido2 hookup is primarily in the cryptsetup glue). But by all means, send a patch that fixes this, we can certainly merge that.

**Comment by wylfen** [comment]
I agree that the specific combination of switches is nonsensical. My main concern is that the build fails by default on systems where `libfido2` is autodetected but `libcryptsetup` isn't. My system just happens to be one of those.

Regardless of the autodetection issue, it would be useful for packagers to know whether upstream wants to support such a combination at all (perhaps some time in the future systemd will use `libfido2` for something other than `systemd-cryptenroll`). As far as I can tell this combination of switches worked up until 253 and was broken silently.

I can certainly provide a patch but am unsure how to fix this. Should meson just refuse to enable `libfido2` if `HAVE_LIBCRYPTSETUP` is false?

**Comment by poettering** [comment]
nah, I'd leave the two knobs independent. just condition out the code where the two subsystems are linked up.
