### PR TITLE
test-copy: use correct data type for max_bytes

### PR DESCRIPTION
**Pull request by martinpitt**
copy_bytes() and the comparisons in test_copy_bytes_regular_file() expect an uint64_t, not a size_t. On 32 bit architectures the latter is 32 bit, leading to truncation errors.

Build on i386 currently fails with

```
../src/test/test-copy.c: In function ‘test_copy_bytes_regular_file’:
../src/test/test-copy.c:202:23: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         if (max_bytes == (uint64_t) -1)
                       ^
../src/test/test-copy.c:210:23: warning: comparison is always false due to limited range of data type [-Wtype-limits]
         if (max_bytes == (uint64_t) -1)
                       ^
../src/test/test-copy.c: In function ‘main’:
../src/test/test-copy.c:236:54: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
         test_copy_bytes_regular_file(argv[0], false, (uint64_t) -1);
                                                      ^
../src/test/test-copy.c:237:53: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
         test_copy_bytes_regular_file(argv[0], true, (uint64_t) -1);
                                                     ^
```

(See https://launchpadlibrarian.net/249167031/buildlog_ubuntu-xenial-i386.systemd_229+upstream20160321-0.ubuntu_BUILDING.txt.gz)

Fixes regression from commit 7a827fcb. @keszybz , can you please have a look? Thanks!

### CODE REVIEW

**Comment by keszybz** [comment]
Yeah, fix looks correct.
