### ISSUE TITLE
/src/boot/efi does not compile with gnu-efi-3.0.10

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#13789]
**systemd version the issue has been seen with**
systemd-243 latest snapshot from v243-stable

**Used distribution**
OpenMandriva Cooker

**Expected behaviour you didn't see**
Compiles with gnu-efi-3.0.10

**Unexpected behaviour you saw**
Decault compiler is LLVM/clang-9.0.x

Full logs can be found here https://abf.openmandriva.org/build_lists/634006
https://github.com/OpenMandrivaAssociation/gnu-efi/
https://github.com/OpenMandrivaAssociation/systemd

```
FAILED: src/boot/efi/disk.c.o 
/usr/bin/clang -c ../src/boot/efi/disk.c -o src/boot/efi/disk.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/disk.c:4:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[533/2684] Generating graphics.c.o with a custom command.
FAILED: src/boot/efi/graphics.c.o 
/usr/bin/clang -c ../src/boot/efi/graphics.c -o src/boot/efi/graphics.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/graphics.c:8:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[534/2684] Compiling C object 'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o'.
[535/2684] Generating dns_type-list.txt with a meson_exe.py custom command.
[536/2684] Generating measure.c.o with a custom command.
FAILED: src/boot/efi/measure.c.o 
/usr/bin/clang -c ../src/boot/efi/measure.c -o src/boot/efi/measure.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/measure.c:6:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[537/2684] Generating pe.c.o with a custom command.
FAILED: src/boot/efi/pe.c.o 
/usr/bin/clang -c ../src/boot/efi/pe.c -o src/boot/efi/pe.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/pe.c:4:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[538/2684] Generating util.c.o with a custom command.
FAILED: src/boot/efi/util.c.o 
/usr/bin/clang -c ../src/boot/efi/util.c -o src/boot/efi/util.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/util.c:4:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[539/2684] Compiling C object 'src/network/70b1c79@@networkd-core@sta/networkd-manager.c.o'.
[540/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-mount.c.o'.
[541/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-patch-uid.c.o'.
[542/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-setuid.c.o'.
[543/2684] Generating console.c.o with a custom command.
FAILED: src/boot/efi/console.c.o 
/usr/bin/clang -c ../src/boot/efi/console.c -o src/boot/efi/console.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/console.c:4:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[544/2684] Linking static target src/core/libcore.a.
[545/2684] Generating crc32.c.o with a custom command.
FAILED: src/boot/efi/crc32.c.o 
/usr/bin/clang -c ../src/boot/efi/crc32.c -o src/boot/efi/crc32.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/crc32.c:43:
In file included from ../src/boot/efi/crc32.h:5:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[546/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-stub-pid1.c.o'.
[547/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-register.c.o'.
[548/2684] Compiling C object 'src/udev/3eb56e7@@udev-core@sta/udev-rules.c.o'.
[549/2684] Generating boot.c.o with a custom command.
FAILED: src/boot/efi/boot.c.o 
/usr/bin/clang -c ../src/boot/efi/boot.c -o src/boot/efi/boot.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/boot.c:5:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[550/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-cgroup.c.o'.
[551/2684] Generating random-seed.c.o with a custom command.
FAILED: src/boot/efi/random-seed.c.o 
/usr/bin/clang -c ../src/boot/efi/random-seed.c -o src/boot/efi/random-seed.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/random-seed.c:2:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[552/2684] Generating sha256.c.o with a custom command.
FAILED: src/boot/efi/sha256.c.o 
/usr/bin/clang -c ../src/boot/efi/sha256.c -o src/boot/efi/sha256.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/sha256.c:24:
In file included from ../src/boot/efi/sha256.h:5:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[553/2684] Generating shim.c.o with a custom command.
FAILED: src/boot/efi/shim.c.o 
/usr/bin/clang -c ../src/boot/efi/shim.c -o src/boot/efi/shim.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/shim.c:12:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[554/2684] Compiling C object 'src/network/70b1c79@@networkd-core@sta/networkd-route.c.o'.
[555/2684] Generating linux.c.o with a custom command.
FAILED: src/boot/efi/linux.c.o 
/usr/bin/clang -c ../src/boot/efi/linux.c -o src/boot/efi/linux.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from ../src/boot/efi/linux.c:4:
In file included from /usr/include/efi/efilib.h:25:
/usr/include/efi/efilink.h:5:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.
[556/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-settings.c.o'.
[557/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-network.c.o'.
[558/2684] Compiling C object 'src/machine/bdfdaa9@@machine-core@sta/machined-dbus.c.o'.
[559/2684] Compiling C object 'src/machine/bdfdaa9@@machine-core@sta/machine-dbus.c.o'.
[560/2684] Compiling C object 'src/nspawn/83b75b8@@nspawn-core@sta/nspawn-oci.c.o'.
[561/2684] Linking target src/udev/libudev.so.1.6.15.
clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
[562/2684] Linking target libsystemd.so.0.27.0.
clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
[563/2684] Linking target src/shared/libsystemd-shared-243.so.
clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ninja: build stopped: subcommand failed.
RPM build errors:
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.e88Fwj (%build)
BUILDSTDERR:     Macro expanded in comment on line 42: %(echo %{version} |cut -d. -f1)-stable branch of
BUILDSTDERR:     Macro expanded in comment on line 230: %{name}-zsh-completion = %{EVRD}
BUILDSTDERR:     Macro expanded in comment on line 238: %sysvinit_release-%sysvinit_release It's provides something
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.e88Fwj (%build)
```

**Steps to reproduce the problem**

**Comment by mrc0mmand** [comment]
This is not a `clang` only issue, as it happens with `gcc` (8.2.1) as well:

```
# ninja -C build
ninja: Entering directory `build'
[561/1554] Generating disk.c.o with a custom command.
FAILED: src/boot/efi/disk.c.o 
cc -c ../src/boot/efi/disk.c -o src/boot/efi/disk.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from /usr/include/efi/efilib.h:25,
                 from ../src/boot/efi/disk.c:4:
/usr/include/efi/efilink.h:5:10: fatal error: stdint.h: No such file or directory
    5 | #include <stdint.h>
      |          ^~~~~~~~~~
compilation terminated.
[566/1554] Generating graphics.c.o with a custom command.
FAILED: src/boot/efi/graphics.c.o 
cc -c ../src/boot/efi/graphics.c -o src/boot/efi/graphics.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
In file included from /usr/include/efi/efilib.h:25,
                 from ../src/boot/efi/graphics.c:8:
/usr/include/efi/efilink.h:5:10: fatal error: stdint.h: No such file or directory
    5 | #include <stdint.h>
      |          ^~~~~~~~~~
compilation terminated.
[570/1554] Generating dns_type-list.txt with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.

```

It actually makes a sense, as with `-nostdinc` and `-isystem` set to EFI's include dir there's no way we can use `stdint.h`.

However, I'm not sure which *side* here is to blame - cc @poettering.

**Comment by javashin** [comment]
same here gentoo gcc 9.2.0-r1 , glibc 2.30

**Comment by poettering** [comment]
hmm, efi headers including stdint.h sounds wrong to me. AFAIK they are really not supposed to include any headers outside of EFI, they come with their own set of types after all.

**Comment by tpgxyz** [comment]
From gnu-efi commit logs
https://sourceforge.net/p/gnu-efi/code/ci/6335e5c697c57d8b5854b8202de3733bcb151ca6/

Second you may consider dropping gnu-efi on when LLVM/clang is used as default compiler

https://dvdhrm.github.io/2019/01/31/goodbye-gnuefi/

**Comment by denbrice** [comment]
gnu-efi upstream reverted the patch that added the stdint.h include just two days ago (since indeed it shouldn't be included as EFI has its own types):
https://sourceforge.net/p/gnu-efi/code/ci/8b2da2c2247af28bd681a9c8e3231559964c80a6/

I was able to successfully build systemd v243-stable while linking to gnu-efi master.
