### ISSUE TITLE
Build failure when assertions are disabled

### ISSUE THREAD

**Issue by N-R-K** [systemd/systemd#29408]
### systemd version the issue has been seen with

254.5

### Used distribution

Gentoo GNU/Linux

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

Build shouldn't fail due to `-DNDEBUG`.

### Unexpected behaviour you saw

When assertions are disabled (via `-NDEBUG` in `$CFLAGS`) then the build fails due to `_FORTIFY_SOURCE` with the following:

```
In function 'openat',
    inlined from 'fd_reopen' at ../systemd-stable-254.5/src/basic/fd-util.c:780:26,
    inlined from 'xopenat' at ../systemd-stable-254.5/src/basic/fs-util.c:1103:24,
    inlined from 'chaseat' at ../systemd-stable-254.5/src/basic/chase.c:357:41:
/usr/include/bits/fcntl2.h:126:11: error: call to '__openat_missing_mode' declared with attribute error: openat with O_CREAT or O_TMPFILE in third argument needs 4 arguments
  126 |           __openat_missing_mode ();
      |           ^
/usr/include/bits/fcntl2.h:126:11: error: call to '__openat_missing_mode' declared with attribute error: openat with O_CREAT or O_TMPFILE in third argument needs 4 arguments
make: *** [/tmp/portage/sys-apps/systemd-utils-254.5/temp/ccKo9Bu9.mk:2: /tmp/portage/sys-apps/systemd-utils-254.5/temp/ccxunhqk.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
```

This issue was introduced in https://github.com/systemd/systemd/pull/26949 and [was noticed](https://github.com/systemd/systemd/pull/26949#issuecomment-1481307203) by @bluca. Then it was "fixed" by adding an assertion to silence the false positive (?). But obviously, this wouldn't work when `-DNDEBUG` is defined.

## Solutions

There's a number of ways to solve this. Two I can think of the top of my mind are:

* Strip the flags unconditionally on top of `assert()`

```diff
 if (isempty(path)) {
 	assert(!FLAGS_SET(open_flags, O_CREAT|O_EXCL));
+	open_flags &= ~(O_CREAT|O_EXCL); /* avoid build failure due to _FORTIFY_SOURCE FP */
 	return fd_reopen(dir_fd, open_flags & ~O_NOFOLLOW);
 }
```

This is straight forward and should be fairly "portable".

* Add some sort of `ASSUME()` macro that usually resolves to `assert` but turns into `__builtin_unreachable()` (if the compiler supports it) when assertions are disabled. This should also provide GCC with the information that this is an "impossible condition" and thus make the error go away.

ping: @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
You can submit a PR to use `assert_se()` instead of `assert()` and that should fix the build failure.
