### ISSUE TITLE
libsystemd/sd-future/fiber fails to compile on musl

### ISSUE THREAD

**Issue by craftyguy** [systemd/systemd#42236]
### systemd version the issue has been seen with

261-dev

### Used distribution

postmarketOS

### Linux kernel version used

7.0.8

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

systemd should compile

### Unexpected behaviour you saw

build fails with:

```
ninja: job failed: cc  -o test-libudev-static-sym test-libudev-static-sym.p/meson-generated_.._src_test_test-libudev-sym.c.o -Wl,--as-needed -Wl,--no-undefined -pie -fstack-protector -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs -Os -fstack-clash-protection -Wformat -Werror=format-security -g -Wl,-rpath,XXXXXXXXXXXXXXXX libudev.a -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,-z,gcs-report-dynamic=none -Wl,--gc-sections -Wl,--warn-common -Wl,--fatal-warnings -Wl,-z,now -Wl,-z,relro -Wl,-z,gcs-report-dynamic=none -Wl,--gc-sections -Wl,--warn-common
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: libudev.a(src_libsystemd_sd-future_fiber.c.o): in function `fiber_init':
/tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:228:(.text+0x7b8): undefined reference to `getcontext'
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: /tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:241:(.text+0x83c): undefined reference to `makecontext'
/usr/lib/gcc/aarch64-alpine-linux-musl/15.2.0/../../../../aarch64-alpine-linux-musl/bin/ld: /tmp/pmbootstrap-local-source-copy/build/../src/libsystemd/sd-future/fiber.c:246:(.text+0x87c): undefined reference to `swapcontext'
collect2: error: ld returned 1 exit status
```

### Steps to reproduce the problem

build systemd on musl-1.2.6

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
bisected to:


commit 8533513aff3cc5bdb03b82ef503489ee8683478e
Author: Daan De Meyer <daan.j.demeyer@gmail.com>
Date:   Wed Nov 12 17:53:47 2025 +0100

    Introduce support for running code in fibers
```

**Comment by daandemeyer** [comment]
```
# musl declares the ucontext.h functions but does not implement them; the fiber bootstrap in
# src/libsystemd/sd-future/fiber.c relies on them, so on musl we have to link to libucontext.
if get_option('libc') == 'musl'
        libucontext = dependency('libucontext')
else
        libucontext = []
endif
```

Not sure why this isn't kicking in but you need libucontext

**Comment by craftyguy** [comment]
@daandemeyer I "fixed" it with:

```
diff --git a/meson.build b/meson.build
index 7294b9b70c..3acaa7423b 100644
--- a/meson.build
+++ b/meson.build
@@ -1834,6 +1834,7 @@ if static_libudev != 'false'
                 install_dir : libdir,
                 link_depends : libudev_sym,
                 dependencies : [libshared_deps,
+                                libucontext,
                                 userspace],
                 c_args : static_libudev_pic ? [] : ['-fno-PIC'],
                 pic : static_libudev_pic)
```

It seems like libudev.a is including the new fiber stuff but isn't being passed -lcontext

**Comment by bluca** [comment]
> [@daandemeyer](https://github.com/daandemeyer) I "fixed" it with:
> 
> ```
> diff --git a/meson.build b/meson.build
> index 7294b9b70c..3acaa7423b 100644
> --- a/meson.build
> +++ b/meson.build
> @@ -1834,6 +1834,7 @@ if static_libudev != 'false'
>                  install_dir : libdir,
>                  link_depends : libudev_sym,
>                  dependencies : [libshared_deps,
> +                                libucontext,
>                                  userspace],
>                  c_args : static_libudev_pic ? [] : ['-fno-PIC'],
>                  pic : static_libudev_pic)
> ```
> 
> It seems like libudev.a is including the new fiber stuff but isn't being passed -lcontext

Can you send a PR?

**Comment by craftyguy** [comment]
looks like Daan already did, I wasn't confident enough that this was the correct fix 😅
