### ISSUE TITLE
build fails if gcrypt support is disabled.

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#7977]
This is with git master v236-636-gdad105c67

Building without gcrypt support (```meson -Dgcrypt=false```) leads to

```
[3/528] Compiling C object 'src/resolve/systemd-resolve-core@sta/resolved-dns-packet.c.o'.
FAILED: src/resolve/systemd-resolve-core@sta/resolved-dns-packet.c.o 
cc  -Isrc/resolve/systemd-resolve-core@sta -Isrc/resolve -I../src/resolve -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/core -I../src/core -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -Isrc/timesync -I../src/timesync -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -ffunction-sections -fdata-sections -include config.h -g -O2 -fdebug-prefix-map=/home/michael/debian/build-area/systemd=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -MMD -MQ 'src/resolve/systemd-resolve-core@sta/resolved-dns-packet.c.o' -MF 'src/resolve/systemd-resolve-core@sta/resolved-dns-packet.c.o.d' -o 'src/resolve/systemd-resolve-core@sta/resolved-dns-packet.c.o' -c ../src/resolve/resolved-dns-packet.c
../src/resolve/resolved-dns-packet.c: In function ‘dns_packet_append_opt’:
../src/resolve/resolved-dns-packet.c:759:5: error: "GCRYPT_VERSION_NUMBER" is not defined, evaluates to 0 [-Werror=undef]
 #if GCRYPT_VERSION_NUMBER >= 0x010600
     ^~~~~~~~~~~~~~~~~~~~~
../src/resolve/resolved-dns-packet.c:770:5: error: "GCRYPT_VERSION_NUMBER" is not defined, evaluates to 0 [-Werror=undef]
 #if GCRYPT_VERSION_NUMBER >= 0x010600
     ^~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
[8/528] Generating sys with a custom command.
ninja: build stopped: subcommand failed.
```

This regression was introduced in 73a4cd17c37f61159a365e55bdd5ff2b8327d439

**Comment by mbiebl** [comment]
Maybe use 
```
diff --git a/src/resolve/resolved-dns-packet.c b/src/resolve/resolved-dns-packet.c
index b6feddba9..2067dd518 100644
--- a/src/resolve/resolved-dns-packet.c
+++ b/src/resolve/resolved-dns-packet.c
@@ -756,7 +756,7 @@ int dns_packet_append_opt(DnsPacket *p, uint16_t max_udp_size, bool edns0_do, in
                 static const uint8_t rfc6975[] = {
 
                         0, 5, /* OPTION_CODE: DAU */
-#if GCRYPT_VERSION_NUMBER >= 0x010600
+#if HAVE_GCRYPT && GCRYPT_VERSION_NUMBER >= 0x010600
                         0, 7, /* LIST_LENGTH */
 #else
                         0, 6, /* LIST_LENGTH */
@@ -767,7 +767,7 @@ int dns_packet_append_opt(DnsPacket *p, uint16_t max_udp_size, bool edns0_do, in
                         DNSSEC_ALGORITHM_RSASHA512,
                         DNSSEC_ALGORITHM_ECDSAP256SHA256,
                         DNSSEC_ALGORITHM_ECDSAP384SHA384,
-#if GCRYPT_VERSION_NUMBER >= 0x010600
+#if HAVE_GCRYPT && GCRYPT_VERSION_NUMBER >= 0x010600
                         DNSSEC_ALGORITHM_ED25519,
 #endif
```

**Comment by yuwata** [comment]
I've created PR #7979 with your patch.
