### ISSUE TITLE
Build error on fedora-rawhide-aarch64

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#19543]
See packit failure in #19542 (https://copr-be.cloud.fedoraproject.org/results/packit/systemd-systemd-19542/fedora-rawhide-aarch64/02173219-systemd/builder-live.log.gz).
```
In file included from ../src/basic/af-list.h:6,
                 from ../src/basic/af-list.c:7:
../src/basic/string-util.h: In function â€˜char_is_ccâ€™:
../src/basic/string-util.h:133:19: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  133 |         return (p >= 0 && p < ' ') || p == 127;
      |                   ^~
cc1: all warnings being treated as errors
```
