### ISSUE TITLE
Build failure with smack disabled

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#26543]
### systemd version the issue has been seen with

master

### Used distribution

own

### Linux kernel version used

6.2.0

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Systemd builds fine with `-Dsmack=false`

### Unexpected behaviour you saw

Build fails if systemd was configured with `-Dsmack=false`

```
../../../src/systemd/src/shared/smack-util.c:256:5: error: redefinition of ‘mac_smack_apply’
  256 | int mac_smack_apply(const char *path, SmackAttr attr, const char *label) {
      |     ^~~~~~~~~~~~~~~
In file included from ../../../src/systemd/src/shared/smack-util.c:22:
../../../src/systemd/src/shared/smack-util.h:42:19: note: previous definition of ‘mac_smack_apply’ with type ‘int(const char *, SmackAttr,  const char *)’
   42 | static inline int mac_smack_apply(const char *path, SmackAttr attr, const char *label) {
      |                   ^~~~~~~~~~~~~~~
```

Caused by https://github.com/systemd/systemd/pull/26465

`#else` path of `#if ENABLE_SMACK`  at https://github.com/systemd/systemd/blob/main/src/shared/smack-util.c#L243 was not handled.

### Steps to reproduce the problem

Just build with `-Dsmack=false`
