### PR TITLE
boot: fix build with gnu-efi older than 3.0.5

### LINKED ISSUE #13226: systemd seems to be failing to compile on Debian Stretch
```
[577/1535] Generating random-seed.c.o with a custom command.
FAILED: src/boot/efi/random-seed.c.o
cc -c ../src/boot/efi/random-seed.c -o src/boot/efi/random-seed.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-comparI
../src/boot/efi/random-seed.c:12:43: error: ‘EFI_RNG_PROTOCOL_GUID’ undeclared here (not in a function)
 static const EFI_GUID rng_protocol_guid = EFI_RNG_PROTOCOL_GUID;
                                           ^~~~~~~~~~~~~~~~~~~~~
../src/boot/efi/random-seed.c: In function ‘acquire_rng’:
../src/boot/efi/random-seed.c:19:9: error: unknown type name ‘EFI_RNG_PROTOCOL’
         EFI_RNG_PROTOCOL *rng;
         ^~~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:35:0,
                 from ../src/boot/efi/random-seed.c:1:
../src/boot/efi/random-seed.c:38:36: error: request for member ‘GetRNG’ in something not a structure or union
         err = uefi_call_wrapper(rng->GetRNG, 3, rng, NULL, size, data);
                                    ^
[579/1535] Generating dns_type-from-name.h with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #13226. But not tested. cc @evverx .

### CODE REVIEW

**Comment by poettering** [comment]
lgtm, let's wait for @evverx' reply though

**Comment by evverx** [comment]
Now it seems to be failing to compile with
```sh
[577/1535] Generating random-seed.c.o with a custom command.
FAILED: src/boot/efi/random-seed.c.o
cc -c ../src/boot/efi/random-seed.c -o src/boot/efi/random-seed.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-comparI
In file included from ../src/boot/efi/random-seed.c:4:0:
../src/boot/efi/missing_efi.h:18:11: error: unknown type name ‘EFI_RNG_ALGORITHM’
   OUT     EFI_RNG_ALGORITHM          *RNGAlgorithmList
           ^~~~~~~~~~~~~~~~~
../src/boot/efi/missing_efi.h:25:11: error: unknown type name ‘EFI_RNG_ALGORITHM’
   IN      EFI_RNG_ALGORITHM          *RNGAlgorithm,           OPTIONAL
           ^~~~~~~~~~~~~~~~~
../src/boot/efi/missing_efi.h:31:11: error: unknown type name ‘EFI_RNG_GET_INFO’
           EFI_RNG_GET_INFO           GetInfo;
           ^~~~~~~~~~~~~~~~
../src/boot/efi/missing_efi.h:32:11: error: unknown type name ‘EFI_RNG_GET_RNG’
           EFI_RNG_GET_RNG            GetRNG;
           ^~~~~~~~~~~~~~~
In file included from /usr/include/efi/efi.h:35:0,
                 from ../src/boot/efi/random-seed.c:1:
../src/boot/efi/random-seed.c: In function ‘acquire_rng’:
../src/boot/efi/random-seed.c:39:33: error: called object is not a function or function pointer
         err = uefi_call_wrapper(rng->GetRNG, 3, rng, NULL, size, data);
                                 ^
[579/1535] Generating shim.c.o with a custom command.
ninja: build stopped: subcommand failed.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

@mbiebl @fsateler before we reimplement half the headers here to get `systemd` to compile on Debian Stretch, I'm wondering if it would be enough to just make `meson` fail if it can't find `EFI_RNG_PROTOCOL_GUID`.

**Comment by yuwata** [comment]
Updated. @evverx Please test again. Thank you.

**Comment by evverx** [comment]
All I can say at this point is that systemd compiles. I kind of tried to run `test-efi` but it seems to have vanished into thin air when we switched to `meson`. `test/test-efi-create-disk.sh` is still in the repository though.

**Comment by poettering** [comment]
ok, let's tag rc1 as soon as this PR finishes CI...

**Comment by poettering** [comment]
@mrc0mmand somethngs's strange with the centos CI here?

**Comment by keszybz** [comment]
```
Tracer caught signal 11: addr=0x0 pc=0x7fad92aafba8 sp=0x7fad8b5ced00
==11065==LeakSanitizer has encountered a fatal error.
```

**Comment by mrc0mmand** [comment]
As I mentioned on Telegram, the LSan issue is definitely not relevant, as I've seen it a couple of times before. I'll have to look into that though...

**Comment by keszybz** [comment]
bionic-i386 passed, so the build issues seems to be fixed.
