### ISSUE TITLE
build failure if building with -Ddns-over-tls=openssl

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#18639]
**systemd version the issue has been seen with**
master 

**Expected behaviour you didn't see**
 clean build

**Unexpected behaviour you saw**
 build fails

**Steps to reproduce the problem**
 build systemd with -Dopenssl=true -Ddns-over-tls=openssl

**Additional program output to the terminal or log subsystem illustrating the issue**

```
In file included from ../../../src/systemd/src/basic/io-util.h:10,
                 from ../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:11:
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c: In function ‘SSL_freep’:
../../../src/systemd/src/basic/macro.h:412:28: error: void value not ignored as it ought to be
  412 |                         *p = func(*p);                          \
      |                            ^
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:16:1: note: in expansion of macro ‘DEFINE_TRIVIAL_CLEANUP_FUNC’
   16 | DEFINE_TRIVIAL_CLEANUP_FUNC(SSL*, SSL_free);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c: In function ‘BIO_freep’:
../../../src/systemd/src/basic/macro.h:412:28: warning: assignment to ‘BIO *’ {aka ‘struct bio_st *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  412 |                         *p = func(*p);                          \
      |                            ^
../../../src/systemd/src/resolve/resolved-dnstls-openssl.c:17:1: note: in expansion of macro ‘DEFINE_TRIVIAL_CLEANUP_FUNC’
   17 | DEFINE_TRIVIAL_CLEANUP_FUNC(BIO*, BIO_free);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Seems to be caused by https://github.com/systemd/systemd/commit/fd421c4adc7406de02e03e2f7ceede2cc6e1d9d4 ,
it looks like resolved-dnstls-openssl.c was not updated.

This patch fixes the issue for me:
```
diff --git a/src/resolve/resolved-dnstls-openssl.c b/src/resolve/resolved-dnstls-openssl.c
index defddb5237..17af90d4cc 100644
--- a/src/resolve/resolved-dnstls-openssl.c
+++ b/src/resolve/resolved-dnstls-openssl.c
@@ -13,8 +13,8 @@
 #include "resolved-dnstls.h"
 #include "resolved-manager.h"

-DEFINE_TRIVIAL_CLEANUP_FUNC(SSL*, SSL_free);
-DEFINE_TRIVIAL_CLEANUP_FUNC(BIO*, BIO_free);
+DEFINE_TRIVIAL_CLEANUP_FUNC_FULL(SSL*, SSL_free, NULL);
+DEFINE_TRIVIAL_CLEANUP_FUNC_FULL(BIO*, BIO_free, NULL);

 static int dnstls_flush_write_buffer(DnsStream *stream) {
         ssize_t ss;
```

However as I have no idea about crypto stuff I'm hesitant to PR this fix.
