### PR TITLE
core: derive restrict-fsaccess initramfs_s_dev offset from skeleton

### LINKED ISSUE #42689: Build failure with `-Dbpf=enabled -Dbpf_compiler=gcc`
### systemd version the issue has been seen with

261

### Used distribution

Gentoo

### Linux kernel version used

7.0.12

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Successful build.

### Unexpected behaviour you saw

Failed build.

### Steps to reproduce the problem

1. Install a GCC cross-compiler for bpf. I used one based on GCC 16.1.
2. `meson setup -Dbpf=enabled -Dbpf_compiler=gcc`
3. `ninja -C build`

### Additional program output to the terminal or log subsystem illustrating the issue

Originally reported downstream in Gentoo at https://bugs.gentoo.org/977839.

The build fails with:
```sh

FAILED: [code=1] src/core/libsystemd-core-261.a.p/bpf-restrict-fsaccess.c.o 
x86_64-pc-linux-gnu-gcc -Isrc/core/libsystemd-core-261.a.p -Isrc/core -I../systemd-261/src/core -Isrc/shared -I../systemd-261/src/shared -Isrc/bpf -I../systemd-261/src/bpf -I../systemd-261/src/libsystemd/sd-bus -I../systemd-261/src/libsystemd/sd-common -I../systemd-261/src/libsystemd/sd-device -I../systemd-261/src/libsystemd/sd-event -I../systemd-261/src/libsystemd/sd-future -I../systemd-261/src/libsystemd/sd-hwdb -I../systemd-261/src/libsystemd/sd-id128 -Isrc/libsystemd/sd-journal -I../systemd-261/src/libsystemd/sd-journal -I../systemd-261/src/libsystemd/sd-json -I../systemd-261/src/libsystemd/sd-netlink -I../systemd-261/src/libsystemd/sd-network -I../systemd-261/src/libsystemd/sd-path -I../systemd-261/src/libsystemd/sd-resolve -I../systemd-261/src/libsystemd/sd-varlink -Isrc/basic -I../systemd-261/src/basic -Isrc/fundamental -I../systemd-261/src/fundamental -Isrc/systemd -I../systemd-261/src/systemd -Isrc/version -I../systemd-261/src/version -I/usr/include/uuid -I/usr/include/json-c -I/usr/include/blkid -I/usr/include/libmount -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu17 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-nonnull-compare -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=bool-compare -Werror=discarded-qualifiers -Werror=flex-array-member-not-at-end -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=missing-declarations -Werror=missing-parameter-name -Werror=missing-prototypes -Werror=overflow -Werror=override-init -Werror=pointer-sign -Werror=return-type -Werror=sequence-point -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=strict-flex-arrays -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunterminated-string-initialization -Wunused-function -Wwrite-strings -Wzero-as-null-pointer-constant -Wzero-length-bounds -fdiagnostics-show-option -fexcess-precision=standard -fno-common -fstack-protector -fstack-protector-strong -fstrict-flex-arrays=3 -fno-math-errno --param=ssp-buffer-size=4 -Wno-maybe-uninitialized -Wno-unused-result -ftrivial-auto-var-init=zero -Werror=shadow -O2 -pipe -mtune=native -march=native -fPIC -fno-strict-aliasing -fstrict-flex-arrays=1 -fvisibility=hidden -include config.h -isystem../systemd-261/src/include/glibc -isystem../systemd-261/src/include/override -isystemsrc/include/override -isystem../systemd-261/src/include/uapi -fvisibility=default -MD -MQ src/core/libsystemd-core-261.a.p/bpf-restrict-fsaccess.c.o -MF src/core/libsystemd-core-261.a.p/bpf-restrict-fsaccess.c.o.d -o src/core/libsystemd-core-261.a.p/bpf-restrict-fsaccess.c.o -c ../systemd-261/src/core/bpf-restrict-fsaccess.c
In file included from ../systemd-261/src/basic/../fundamental/assert-util.h:8,
                 from ../systemd-261/src/basic/cleanup-util.h:4,
                 from ../systemd-261/src/shared/conf-parser-forward.h:4,
                 from ../systemd-261/src/core/core-forward.h:6,
                 from ../systemd-261/src/core/bpf-restrict-fsaccess.h:6,
                 from ../systemd-261/src/core/bpf-restrict-fsaccess.c:7:
../systemd-261/src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), initramfs_s_dev)"
  154 | #define assert_cc(expr) _Static_assert(expr, #expr)
      |                         ^~~~~~~~~~~~~~
../systemd-261/src/core/bpf-restrict-fsaccess.c:58:1: note: in expansion of macro ‘assert_cc’
   58 | assert_cc(offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) ==
      | ^~~~~~~~~
../systemd-261/src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), protected_map_id_verity)"
  154 | #define assert_cc(expr) _Static_assert(expr, #expr)
      |                         ^~~~~~~~~~~~~~
../systemd-261/src/core/bpf-restrict-fsaccess.c:60:1: note: in expansion of macro ‘assert_cc’
   60 | assert_cc(offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) ==
      | ^~~~~~~~~
```

The user's full build log is at https://bugs.gentoo.org/attachment.cgi?id=965211 but I can reproduce it myself.

The assert comes from 68fe7fa4d62cf777a4be1df00761e27b21754b1b (https://github.com/systemd/systemd/pull/41340/changes#diff-879a826a98248d9f9b686f398b67397171449d2910463023674e185387fee629R51) (cc @brauner).

### PR DESCRIPTION
**Pull request by TuNaiChao**
Fixes #42689.

Building with `-Dbpf=enabled -Dbpf_compiler=gcc` (GCC's BPF backend) fails on the static assertions in `bpf-restrict-fsaccess.c` (introduced by 68fe7fa4d6 / #41340):

```
macro.h:154:25: error: static assertion failed:
"offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) ==
 offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), initramfs_s_dev)"
```

### Root cause

`struct restrict_fsaccess_bss` is a hand-maintained mirror of the BPF program's `.bss` section, with fields listed in source-declaration order. It is checked against the skeleton's generated `bss` struct via `assert_cc(offsetof(...) == offsetof(...))`.

`bpftool gen skeleton` emits the skeleton struct from the BTF `.bss` DATASEC, whose member order reflects the *physical* order the compiler placed the variables in the section — not the source order. Clang's BPF backend preserves declaration order, so the assertions hold. GCC's BPF backend reorders `.bss`/`.data` globals (by alignment class, etc.), so `initramfs_s_dev` no longer sits at offset 0 and the build breaks.

### Why this is a correctness bug, not just a build break

`restrict_fsaccess_clear_initramfs_trust()` closes the initramfs trust window after `switch_root` by `mmap()`ing the `.bss` map and writing `0` at a **hardcoded offset 0**:

```c
assert_cc(offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) == 0);
...
*(uint32_t *) p = 0;
```

Under the GCC layout that store would land on the wrong global, silently leaving `initramfs_s_dev` set — i.e. the initramfs trust window stays open after `switch_root` instead of being closed. The `assert_cc`s were correctly catching this; simply deleting them to make the GCC build pass would introduce the bug.

### Fix

Stop maintaining a parallel mirror struct and use the generated skeleton as the single source of truth for the offset:

- Drop `struct restrict_fsaccess_bss` and the four field-order `assert_cc()`s.
- Take the offset from the skeleton: `INITRAMFS_S_DEV_OFF = offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), initramfs_s_dev)` — a compile-time constant that tracks whatever the BPF compiler (clang *or* gcc) actually emitted.
- Store at `p + INITRAMFS_S_DEV_OFF` instead of `p + 0`.
- Keep one `assert_cc(INITRAMFS_S_DEV_OFF % sizeof(uint32_t) == 0)` documenting the 4-byte alignment the single-store atomicity relies on.

All other accesses already go through `obj->bss->...` (the skeleton struct) and were already compiler-correct; only this one mmap-based path assumed offset 0. With clang the offset is still 0, so behaviour is unchanged; with gcc the correct field is cleared.

### Verification

I don't have a BPF toolchain locally, so I verified the mechanism with a standalone model covering both a clang-style (declaration-order) and a gcc-style (reordered) skeleton layout: the skeleton-derived offset clears `initramfs_s_dev` and leaves the guard globals intact in both cases, whereas a hardcoded offset 0 under the GCC layout clobbers `protected_prog_ids[0]` and leaves `initramfs_s_dev` set. A CI pass on a `bpf_compiler=gcc` configuration would be appreciated.

Signed-off-by: tunaichao <tunaichao@uniontech.com>
Assistant: glm-5.2

### CODE REVIEW

**Review by brauner — APPROVED** [review]

**Comment by lionheartyu** [comment]
Good fix. However, for the reproduction steps and the root cause, you can refer to this draft PR of mine.
My PR is merely for reference.https://github.com/systemd/systemd/pull/42706 not merge

**Comment by TuNaiChao** [comment]
Thanks for the review.

**Comment by TuNaiChao** [comment]
Verified locally on GCC's BPF backend. The failure is `.bss` field **reordering**,
not padding — so `aligned(4)` would not fix it. This PR does, and I confirmed it
compiles.

### Environment
- Fedora 42 container, systemd `262~devel`
- `bpf-unknown-none-gcc` 15.2.1 (Red Hat Cross), `bpftool` 7.5.0, `libbpf` 1.5.0

### 1. Reproduce (pre-fix tree)

    $ meson setup -Dbpf-framework=enabled -Dbpf-compiler=gcc build-gcc && meson compile -C build-gcc
    ...
     config.h -DWITH_GZFILEOP -isystem../src/include/glibc -isystem../src/include/override -isystemsrc/include/override -isystem../src/include/uapi -fvisibility=default -MD -MQ src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o -MF src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o.d -o src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o -c ../src/core/bpf-restrict-fsaccess.c
    In file included from ../src/basic/../fundamental/assert-util.h:8,
                     from ../src/basic/cleanup-util.h:4,
                     from ../src/shared/conf-parser-forward.h:4,
                     from ../src/core/core-forward.h:6,
                     from ../src/core/bpf-restrict-fsaccess.h:6,
                     from ../src/core/bpf-restrict-fsaccess.c:7:
    ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), initramfs_s_dev)"
      154 | #define assert_cc(expr) _Static_assert(expr, #expr)
          |                         ^~~~~~~~~~~~~~
    ../src/core/bpf-restrict-fsaccess.c:58:1: note: in expansion of macro ‘assert_cc’
       58 | assert_cc(offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) ==
          | ^~~~~~~~~
    ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), protected_map_id_verity)"
      154 | #define assert_cc(expr) _Static_assert(expr, #expr)
          |                         ^~~~~~~~~~~~~~
    ../src/core/bpf-restrict-fsaccess.c:60:1: note: in expansion of macro ‘assert_cc’
       60 | assert_cc(offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) ==
          | ^~~~~~~~~
    ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, protected_map_id_bss) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), protected_map_id_bss)"
      154 | #define assert_cc(expr) _Static_assert(expr, #expr)
          |                         ^~~~~~~~~~~~~~
    ../src/core/bpf-restrict-fsaccess.c:62:1: note: in expansion of macro ‘assert_cc’
       62 | assert_cc(offsetof(struct restrict_fsaccess_bss, protected_map_id_bss) ==
          | ^~~~~~~~~
    [576/2569] Compiling C object src/core/libsystemd-core-262.a.p/cgroup.c.o
    ninja: build stopped: subcommand failed.

Note that all three asserts fail — `initramfs_s_dev` (line 58), not only the
`protected_map_id_*` pair.

### 2. Root cause — GCC's actual `.bss` layout (from the generated skeleton)

    struct restrict_fsaccess_bpf__bss {
            __u32 protected_link_ids[9];   /*  0 */
            __u32 protected_prog_ids[9];   /* 36 */
            __u32 protected_map_id_bss;    /* 72 */
            __u32 protected_map_id_verity; /* 76 */
            __u32 initramfs_s_dev;         /* 80  <-- last, not first */
    } *bss;

| field                   | mirror (decl order) | gcc skeleton |
| ----------------------- | ------------------: | -----------: |
| initramfs_s_dev         |                   0 |           80 |
| protected_map_id_verity |                   4 |           76 |
| protected_map_id_bss    |                   8 |           72 |
| **sizeof**              |               **84** |       **84** |

GCC emits the globals in **reverse declaration order**. `sizeof` matches (84)
yet every field offset differs → a padding-free permutation, not padding.
Padding cannot move the first field off offset 0, so `initramfs_s_dev` at 80
proves reordering. (Consequently the old offset-0 store would have hit
`protected_link_ids[0]` and left `initramfs_s_dev` set — the latent
trust-window bug the asserts were guarding.)

### 3. Verification (this PR)

    $ meson setup -Dbpf-framework=enabled -Dbpf-compiler=gcc build-gcc && meson compile -C build-gcc
    ...
    $ ls -l build-gcc/src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o
    -rw-r--r-- 1 root root 199624  .../bpf-restrict-fsaccess.c.o

`bpf-restrict-fsaccess.c` compiles cleanly under `bpf-unknown-none-gcc` 15.2.1 —
`INITRAMFS_S_DEV_OFF` resolves to 80 (gcc) / 0 (clang), no assertion failure.

`aligned(4)` only affects alignment (there is no padding here to remove) and
cannot restore field order, so it does not clear the assertions. Deriving the
offset from the generated skeleton is the correct fix and is verified on the
gcc backend; clang is unchanged.

**Comment by thesamesam** [comment]
Thanks, I've tested this now too and it works (and tests pass).

**Comment by lionheartyu** [comment]
> Verified locally on GCC's BPF backend. The failure is `.bss` field **reordering**, not padding — so `aligned(4)` would not fix it. This PR does, and I confirmed it compiles.
> 
> ### Environment
> * Fedora 42 container, systemd `262~devel`
> * `bpf-unknown-none-gcc` 15.2.1 (Red Hat Cross), `bpftool` 7.5.0, `libbpf` 1.5.0
> 
> ### 1. Reproduce (pre-fix tree)
> ```
> $ meson setup -Dbpf-framework=enabled -Dbpf-compiler=gcc build-gcc && meson compile -C build-gcc
> ...
>  config.h -DWITH_GZFILEOP -isystem../src/include/glibc -isystem../src/include/override -isystemsrc/include/override -isystem../src/include/uapi -fvisibility=default -MD -MQ src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o -MF src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o.d -o src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o -c ../src/core/bpf-restrict-fsaccess.c
> In file included from ../src/basic/../fundamental/assert-util.h:8,
>                  from ../src/basic/cleanup-util.h:4,
>                  from ../src/shared/conf-parser-forward.h:4,
>                  from ../src/core/core-forward.h:6,
>                  from ../src/core/bpf-restrict-fsaccess.h:6,
>                  from ../src/core/bpf-restrict-fsaccess.c:7:
> ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), initramfs_s_dev)"
>   154 | #define assert_cc(expr) _Static_assert(expr, #expr)
>       |                         ^~~~~~~~~~~~~~
> ../src/core/bpf-restrict-fsaccess.c:58:1: note: in expansion of macro ‘assert_cc’
>    58 | assert_cc(offsetof(struct restrict_fsaccess_bss, initramfs_s_dev) ==
>       | ^~~~~~~~~
> ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), protected_map_id_verity)"
>   154 | #define assert_cc(expr) _Static_assert(expr, #expr)
>       |                         ^~~~~~~~~~~~~~
> ../src/core/bpf-restrict-fsaccess.c:60:1: note: in expansion of macro ‘assert_cc’
>    60 | assert_cc(offsetof(struct restrict_fsaccess_bss, protected_map_id_verity) ==
>       | ^~~~~~~~~
> ../src/basic/../fundamental/macro.h:154:25: error: static assertion failed: "offsetof(struct restrict_fsaccess_bss, protected_map_id_bss) == offsetof(typeof_field(struct restrict_fsaccess_bpf, bss[0]), protected_map_id_bss)"
>   154 | #define assert_cc(expr) _Static_assert(expr, #expr)
>       |                         ^~~~~~~~~~~~~~
> ../src/core/bpf-restrict-fsaccess.c:62:1: note: in expansion of macro ‘assert_cc’
>    62 | assert_cc(offsetof(struct restrict_fsaccess_bss, protected_map_id_bss) ==
>       | ^~~~~~~~~
> [576/2569] Compiling C object src/core/libsystemd-core-262.a.p/cgroup.c.o
> ninja: build stopped: subcommand failed.
> ```
> 
> Note that all three asserts fail — `initramfs_s_dev` (line 58), not only the `protected_map_id_*` pair.
> 
> ### 2. Root cause — GCC's actual `.bss` layout (from the generated skeleton)
> ```
> struct restrict_fsaccess_bpf__bss {
>         __u32 protected_link_ids[9];   /*  0 */
>         __u32 protected_prog_ids[9];   /* 36 */
>         __u32 protected_map_id_bss;    /* 72 */
>         __u32 protected_map_id_verity; /* 76 */
>         __u32 initramfs_s_dev;         /* 80  <-- last, not first */
> } *bss;
> ```
> 
> field	mirror (decl order)	gcc skeleton
> initramfs_s_dev	0	80
> protected_map_id_verity	4	76
> protected_map_id_bss	8	72
> **sizeof**	**84**	**84**
> GCC emits the globals in **reverse declaration order**. `sizeof` matches (84) yet every field offset differs → a padding-free permutation, not padding. Padding cannot move the first field off offset 0, so `initramfs_s_dev` at 80 proves reordering. (Consequently the old offset-0 store would have hit `protected_link_ids[0]` and left `initramfs_s_dev` set — the latent trust-window bug the asserts were guarding.)
> 
> ### 3. Verification (this PR)
> ```
> $ meson setup -Dbpf-framework=enabled -Dbpf-compiler=gcc build-gcc && meson compile -C build-gcc
> ...
> $ ls -l build-gcc/src/core/libsystemd-core-262.a.p/bpf-restrict-fsaccess.c.o
> -rw-r--r-- 1 root root 199624  .../bpf-restrict-fsaccess.c.o
> ```
> 
> `bpf-restrict-fsaccess.c` compiles cleanly under `bpf-unknown-none-gcc` 15.2.1 — `INITRAMFS_S_DEV_OFF` resolves to 80 (gcc) / 0 (clang), no assertion failure.
> 
> `aligned(4)` only affects alignment (there is no padding here to remove) and cannot restore field order, so it does not clear the assertions. Deriving the offset from the generated skeleton is the correct fix and is verified on the gcc backend; clang is unchanged.

A good verification method

**Comment by TuNaiChao** [comment]
> Thanks, I've tested this now too and it works (and tests pass).

Thank you for taking the time to test it. I'm glad to hear that it works on your side as well.

**Review by keszybz — APPROVED** [review]
LGTM.
