### PR TITLE
basic/linux: update l2tp.h

### PR DESCRIPTION
**Pull request by mrc0mmand**
IPPROTO_L2TP was moved from linux/l2tp.h to linux/in.h [0], so let's reflect that change to fix build with newer kernels:

```
In file included from ../src/libsystemd/sd-netlink/netlink-types-genl.c:10:
../src/basic/linux/l2tp.h:16: error: "IPPROTO_L2TP" redefined [-Werror]
   16 | #define IPPROTO_L2TP            115
      |
In file included from ../src/libsystemd/sd-netlink/netlink-types-genl.c:3:
/usr/include/netinet/in.h:85: note: this is the location of the previous definition
   85 | #define IPPROTO_L2TP            IPPROTO_L2TP
      |
cc1: all warnings being treated as errors
```

[0] https://github.com/torvalds/linux/commit/65b32f801bfbc54dc98144a6ec26082b59d131ee

### CODE REVIEW

**Comment by yuwata** [comment]
Is it not necessary to pick the change for in.h ?

BTW, in src/basic/linux, there is a tiny script to update all headers. I think it is better to update all headers now, if the kernel upstream made a spurious change.

**Comment by mrc0mmand** [comment]
> Is it not necessary to pick the change for in.h ?

Ah, indeed, I completely overlooked that we have `in.h` as well.
> 
> BTW, in src/basic/linux, there is a tiny script to update all headers. I think it is better to update all headers now, if the kernel upstream made a spurious change.

*sigh*, I was looking for that script but couldn't find it anywhere, thanks!

**Comment by mrc0mmand** [comment]
Syncing the linux/btrfs.h header introduced more "fun", but I'm not sure if my solution is correct/optimal, see the second commit.

**Comment by mrc0mmand** [comment]
> Syncing the linux/btrfs.h header introduced more "fun", but I'm not sure if my solution is correct/optimal, see the second commit.

Minimal reproducer:

```c
#include <linux/btrfs.h>
#include <linux/fs.h>
#include <sys/mount.h>
#include <stdio.h>

int main(void) {
    printf("%d\n", MS_RDONLY);

    return 0;
}
```

```
$ gcc -o test test.c
In file included from /usr/include/linux/fs.h:19,
                 from test.c:3:
/usr/include/sys/mount.h:35:3: error: expected identifier before numeric constant
   35 |   MS_RDONLY = 1,                /* Mount read-only.  */
      |   ^~~~~~~~~
In file included from test.c:4:
test.c: In function ‘main’:
test.c:8:20: error: ‘MS_RDONLY’ undeclared (first use in this function)
    8 |     printf("%d\n", MS_RDONLY);
      |                    ^~~~~~~~~
test.c:8:20: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by mrc0mmand** [comment]
Also, looks like Debian is missing the `__DECLARE_FLEX_ARRAY()` helper introduced in https://github.com/torvalds/linux/commit/3080ea5553cc909b000d1f1d964a9041962f2c5b so we will need to pull `linux/stddef.h` as well?

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
Looks reasonable. If it builds, ship it!
