### PR TITLE
efivars: include errno.h when EFI support is disabled

### LINKED ISSUE #7898: Build failure regression if efi is disabled.
### Submission type

 - Bug report

### systemd version the issue has been seen with

master

### Used distribution

custom, embedded arm 32 bit
```

         enabled features: PAM, zlib, xz, lz4, bzip2, ACL, gcrypt, qrencode, microhttpd, gnutls, libcurl, idn, libidn2, nss-systemd, elfutils, vconsole, tmpfiles, environment.d, randomseed, rfkill, logind, hostnamed, timedated, timesyncd, localed, networkd, resolve, coredump, polkit, kmod, blkid, glib, nss-myhostname, hwdb, man pages, man page indices, utmp, ldconfig, adm group, gshadow

         disabled features: libcryptsetup, AUDIT, IMA, AppArmor, SELinux, SECCOMP, SMACK, libidn, libiptc, binfmt, quotacheck, sysusers, firstboot, backlight, machined, importd, legacy pkla, efi, gnu-efi, xkbcommon, dbus, tpm, html pages, split /usr, SysV compat, hibernate, wheel group, debug hashmap, debug mmap cache
```
Note efi and gnu-efi disabled (the board is not uefi compatible)
### In case of bug report: Expected behaviour you didn't see

systemd builds fine

### In case of bug report: Unexpected behaviour you saw

build fails if systemd is configured without efi support
```
In file included from ../../../src/systemd/src/shared/boot-timestamps.c:24:0:
../../../src/systemd/src/shared/efivars.h: In function ‘efi_reboot_to_firmware_supported’:
../../../src/systemd/src/shared/efivars.h:75:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h:75:17: note: each undeclared identifier is reported only once for each function it appears in
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_reboot_to_firmware’:
../../../src/systemd/src/shared/efivars.h:79:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_set_reboot_to_firmware’:
../../../src/systemd/src/shared/efivars.h:83:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_variable’:
../../../src/systemd/src/shared/efivars.h:87:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_set_variable’:
../../../src/systemd/src/shared/efivars.h:91:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_variable_string’:
../../../src/systemd/src/shared/efivars.h:95:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_boot_option’:
../../../src/systemd/src/shared/efivars.h:99:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_add_boot_option’:
../../../src/systemd/src/shared/efivars.h:103:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_remove_boot_option’:
../../../src/systemd/src/shared/efivars.h:107:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_boot_order’:
../../../src/systemd/src/shared/efivars.h:111:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_set_boot_order’:
../../../src/systemd/src/shared/efivars.h:115:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_get_boot_options’:
../../../src/systemd/src/shared/efivars.h:119:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_loader_get_device_part_uuid’:
../../../src/systemd/src/shared/efivars.h:123:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
../../../src/systemd/src/shared/efivars.h: In function ‘efi_loader_get_boot_usec’:
../../../src/systemd/src/shared/efivars.h:127:17: error: ‘EOPNOTSUPP’ undeclared (first use in this function)
         return -EOPNOTSUPP;
                 ^~~~~~~~~~
```
### In case of bug report: Steps to reproduce the problem

configure with `-Defi=false`

Regression seems to have been introduced in #7855 

Side note: I consider CI to be pretty useless if it can't catch build errors with different configurations.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #7898.

### CODE REVIEW

**Comment by poettering** [comment]
i probably would have included errno.h unconditionally, but this works too
