### ISSUE TITLE
build with meson fails with ld.bfd (using -Dlink-udev-shared=false -Db_lto=true)

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#5828]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> git master

I reconfigured the xenial-s390x CI build to use meson instead of autotools. This currently fails to build ([example log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/s390x/s/systemd-upstream/20170427_101741_d8343@/log.gz)), mostly on missing libpthread and libselinux libs, but also a rather weird size check failure:

```
In function ‘__read_alias’,
    inlined from ‘compress_stream_xz’ at ../src/journal/compress.c:398:27:
/usr/include/s390x-linux-gnu/bits/unistd.h:39:9: warning: call to ‘__read_chk_warn’ declared with attribute warning: read called with bigger length than size of the destination buffer
  return __read_chk (__fd, __buf, __nbytes, __bos0 (__buf));
         ^
In function ‘__ppoll_alias’,
    inlined from ‘bus_poll’ at ../src/libsystemd/sd-bus/sd-bus.c:2915:11:
/usr/include/s390x-linux-gnu/bits/poll2.h:71:9: warning: call to ‘__ppoll_chk_warn’ declared with attribute warning: ppoll called with fds buffer too small file nfds entries
  return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));

FAILED: systemd-getty-generator 
cc  -o systemd-getty-generator 'systemd-getty-generator@exe/src_getty-generator_getty-generator.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/libudev'  
/tmp/cclLTKce.ltrans3.ltrans.o: In function `mac_selinux_create_file_clear':
/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/../src/basic/selinux-util.c:374: undefined reference to `setfscreatecon_raw'
/tmp/cclLTKce.ltrans3.ltrans.o: In function `mac_selinux_have':
/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/../src/basic/selinux-util.c:59: undefined reference to `is_selinux_enabled'
collect2: error: ld returned 1 exit status

FAILED: systemd-sysusers 
cc  -o systemd-sysusers 'systemd-sysusers@exe/src_sysusers_sysusers.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/libudev'  
/usr/bin/ld: /tmp/ccpz1SmY.ltrans0.ltrans.o: undefined reference to symbol 'selabel_open'
//lib/s390x-linux-gnu/libselinux.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

FAILED: busctl 
cc  -o busctl 'busctl@exe/src_busctl_busctl.c.o' 'busctl@exe/src_busctl_busctl-introspect.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/libudev'  
In function ‘__ppoll_alias’,
    inlined from ‘bus_poll’ at ../src/libsystemd/sd-bus/sd-bus.c:2915:11:
/usr/include/s390x-linux-gnu/bits/poll2.h:71:9: warning: call to ‘__ppoll_chk_warn’ declared with attribute warning: ppoll called with fds buffer too small file nfds entries
  return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));
         ^
/usr/bin/ld: /tmp/ccXySaHU.ltrans17.ltrans.o: undefined reference to symbol 'is_selinux_enabled'
//lib/s390x-linux-gnu/libselinux.so.1: error adding symbols: DSO missing from command line

AILED: systemd-run 
cc  -o systemd-run 'systemd-run@exe/src_run_run.c.o' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.lbwgsqlu/downtmp/build.I3N/debian/build-deb/src/libudev'  
In function ‘__ppoll_alias’,
    inlined from ‘bus_poll’ at ../src/libsystemd/sd-bus/sd-bus.c:2915:11:
/usr/include/s390x-linux-gnu/bits/poll2.h:71:9: warning: call to ‘__ppoll_chk_warn’ declared with attribute warning: ppoll called with fds buffer too small file nfds entries
  return __ppoll_chk (__fds, __nfds, __timeout, __ss, __bos (__fds));
         ^
/usr/bin/ld: /tmp/ccYYGrIZ.ltrans7.ltrans.o: undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2'
//lib/s390x-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by mbiebl** [comment]
I can reproduce the problem on zelenka.d.o, our Debian porterbox, when trying to build in a sid chroot.

It seems to be a result of LTO, dropping ```-Db_lto=true``` from debian/rules makes the build succeed.
Looking at older build logs like [1], it seems like LTO should work, as those builds were using ```-flto```


[1] https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=s390x&ver=232-22&stamp=1490738281&raw=0

**Comment by martinpitt** [comment]
I disabled LTO on s390x for now, but the build is [now failing differently](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/s390x/s/systemd-upstream/20170427_204131_a40c5@/log.gz):
```
FAILED: test-dhcp-client 
cc  -o test-dhcp-client 'test-dhcp-client@exe/src_libsystemd-network_test-dhcp-client.c.o' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/libsystemd-network/libsystemd-network.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.bt2_okfo/downtmp/build.xOe/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.bt2_okfo/downtmp/build.xOe/debian/build-deb/src/libudev'  
/usr/bin/ld: src/libsystemd-network/libsystemd-network.a(dhcp-identifier.c.o): undefined reference to symbol 'udev_device_unref@@LIBUDEV_183'
src/libudev/libudev.so.1.6.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

However, I think that's a regression from PR #5818 now.

**Comment by mbiebl** [comment]
Hm, I certainly tested #5818 and didn't run into such an issue. Somehow this points to difference in the toolchain on s390x which worries me a bit.

**Comment by mbiebl** [comment]
@martinpitt posted a PR at #5850

**Comment by mbiebl** [comment]
@martinpitt Even with this particular issue fixed, we will still run into #5831, so we should get that fixed soonish as well for the CI to be fully operating again

**Comment by mbiebl** [comment]
This issue is not actually fixed. We just worked around it by disabling LTO on s390x

**Comment by mbiebl** [comment]
The build flags needed to reproduce the issue are ```-Dlink-udev-shared=false -Db_lto=true```. The error messages I get
```
ninja: Entering directory `build'
[1/3] Linking target systemd-networkd
FAILED: systemd-networkd 
cc  -o systemd-networkd 'systemd-networkd@exe/networkd.c.o' '-L/' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' 'src/network/libnetworkd-core.a' 'src/shared/libsystemd-shared-233.so' 'src/shared/libsystemd-shared-233.so' 'src/libsystemd-network/libsystemd-network.a' 'src/udev/libudev.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/shared/libsystemd-shared-233.so' '-lrt' '-lcap' '-lacl' '-lcryptsetup' '-lseccomp' '-lselinux' '-lidn' '-llzma' '-llz4' '-lblkid' '-lrt' '-lcap' '-lblkid' '-lselinux' '-Wl,-rpath,/home/biebl/build/systemd-upstream/build/src/shared'  
/usr/bin/ld: /tmp/cc0ZSD2H.ltrans2.ltrans.o: undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2'
//lib/s390x-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[2/3] Linking target test-network
FAILED: test-network 
cc  -o test-network 'test-network@exe/src_network_test-network.c.o' '-L/' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' 'src/network/libnetworkd-core.a' 'src/shared/libsystemd-shared-233.so' 'src/shared/libsystemd-shared-233.so' 'src/udev/libudev.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/libsystemd-network/libsystemd-network.a' 'src/shared/libsystemd-shared-233.so' '-lrt' '-lcap' '-lacl' '-lcryptsetup' '-lseccomp' '-lselinux' '-lidn' '-llzma' '-llz4' '-lblkid' '-lrt' '-lcap' '-lblkid' '-lselinux' '-Wl,-rpath,/home/biebl/build/systemd-upstream/build/src/shared'  
/usr/bin/ld: /tmp/ccY2zpKN.ltrans6.ltrans.o: undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2'
//lib/s390x-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[3/3] Linking target test-network-tables
FAILED: test-network-tables 
cc  -o test-network-tables 'test-network-tables@exe/src_network_test-network-tables.c.o' '-L/' '-flto' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' 'src/network/libnetworkd-core.a' 'src/shared/libsystemd-shared-233.so' 'src/shared/libsystemd-shared-233.so' 'src/udev/libudev.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/udev/libudev-core.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/shared/libsystemd-shared-233.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/libsystemd-network/libsystemd-network.a' 'src/shared/libsystemd-shared-233.so' '-lrt' '-lcap' '-lacl' '-lcryptsetup' '-lseccomp' '-lselinux' '-lidn' '-llzma' '-llz4' '-lblkid' '-lrt' '-lcap' '-lblkid' '-lselinux' '-lblkid' '-lkmod' '-lrt' '-lcap' '-lacl' '-lcryptsetup' '-lseccomp' '-lselinux' '-lidn' '-llzma' '-llz4' '-lblkid' '-lrt' '-lcap' '-lblkid' '-lselinux' '-Wl,-rpath,/home/biebl/build/systemd-upstream/build/src/shared'  
/usr/bin/ld: /tmp/ccJNCezN.ltrans6.ltrans.o: undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2'
//lib/s390x-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by keszybz** [comment]
@mbiebl Seems that this issue is limited to Debian and s390x. Current git builds fine on Fedora rawhide / s390x (https://koji.fedoraproject.org/koji/taskinfo?taskID=19787751). We don't have easy access to the s390x hardware, only through package builds, which makes any kind of debugging rather inconvenient. This one's on you ;)

**Comment by mbiebl** [comment]
@keszybz to reproduce the issue I needed to use ```-Db_lto=true -Dlink-udev-shared=false```. Is the Fedora build using that config?

**Comment by mbiebl** [comment]
@keszybz I'm asking because I'd be interested if that really is a Debian specific toolchain issue

**Comment by mbiebl** [comment]
@keszybz I've filed this downstream as http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863743

Aurelien Jarno tracked this down. Quoting his email:
The problem is related to the fact that gold is not available on s390x.
It seems gold is less strict than ld in having to link with each used
library. The problem can be fully reproduced on amd64 by using ld instead
of gold:

```
--- a/meson.build
+++ b/meson.build
@@ -312,7 +312,7 @@ link_test_c = files('tools/meson-link-test.c')
 foreach arg : ['-Wl,-z,relro',
                '-Wl,-z,now',
                '-pie',
-               '-Wl,-fuse-ld=gold',
+               '-Wl,-fuse-ld=ld',
               ]
 
         have = run_command(check_compilation_sh,
```

Now to come back to the problem, the test is linked against
src/libsystemd/libsystemd.a which uses pthread_sigmask. It looks
therefore normal to add -lpthread to link it.

**Comment by mbiebl** [comment]
I can confirm that it also is easily reproducible on amd64 following these steps:
```
sed -i s/fuse-ld=gold/fuse-ld=ld/ meson.build
meson -Db_lto=true -Dlink-udev-shared=false build
ninja -C build
```

**Comment by mbiebl** [comment]
I wonder if https://github.com/mesonbuild/meson/issues/1426 is related

**Comment by mbiebl** [comment]
@nirbheek can you chime in here. How would you suggest this is fixed/worked around in systemd?

**Comment by nirbheek** [comment]
That bug is about *static library* thread dependencies not being propagated transitively which is not what's happening here because the thread dependency is in `libshared` which is a shared library.

This bug seems to be about GNU `ld.bfd` (once again) being the silliest linker of them all. Out of interest, what version of ld is s390 using? This might become much more relevant with the 0.41 release which completely avoids adding transitive dependencies when linking to shared libraries (which is the correct thing to do). If this breaks older ld, we need to know. Alternatively, if this only breaks with pthread (on all ld.bfd versions), that's even more interesting.

To fix this properly, you would need to add the thread dependency everywhere, but that is unreasonable. So what you can do is to check in the beginning whether `b_lto` is enabled, and if so, add `-pthread` to the project link arguments.

Admittedly this is a hack, but even if we work around this linker bug in Meson you'll still need to carry that patch.

**Comment by mbiebl** [comment]
@nirbheek 
```
$ ld --version
GNU ld (GNU Binutils for Debian) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
And from the Debian changelog:
```
binutils (2.28-6) unstable; urgency=medium

  * Update, taken from the 2.28 branch 20170615.
```

**Comment by nirbheek** [comment]
Okay, so it's probably just `-pthread + ld.bfd` then. Will look into this on the Meson side.

As an aside, do you think it's possible for systemd to run one (or some) of its CI builds with the latest meson master? We have a strongly review-based and test-driven development model, and our aim is to catch regressions early and keep master always-usable. It would really help if we had early-warnings for regressions from large projects like systemd. GStreamer [already does this](https://ci.gstreamer.net/job/GStreamer-master-meson/) and it's quite useful.

**Comment by mbiebl** [comment]
/CC @martinpitt looping Martin in, he's our CI expert

**Comment by mbiebl** [comment]
looking at the build failure from https://github.com/systemd/systemd/issues/5828#issuecomment-304972259 I see
```
cc  -o systemd-networkd 'systemd-networkd@exe/networkd.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -pie -Wl,-fuse-ld=ld -Wl,--start-group src/network/libnetworkd-core.a src/shared/libsystemd-shared-233.so src/libsystemd-network/libsystemd-network.a src/udev/libudev.a src/shared/libsystemd-shared-233.a
```
So it tries to link systemd-networkd against both libsystemd-shared-233.so and libsystemd-shared-233.a.
Isn't that kinda strange?

**Comment by nirbheek** [comment]
That seems to be a problem in systemd's build files:

```meson
if get_option('link-udev-shared')
        udev_link_with = [libshared]
        udev_rpath = rootlibexecdir
else
        udev_link_with = [libshared_static,
                          libsystemd_internal]
        udev_rpath = ''
endif

libudev_internal = static_library(
        'udev',
        libudev_sources,
        include_directories : includes,
        link_with : udev_link_with)
```

and

```meson
executable('systemd-networkd',             
           systemd_networkd_sources,       
           include_directories : includes, 
           link_with : [libnetworkd_core,  
                        libsystemd_network,
                        libudev_internal,  
                        libshared],        
           install_rpath : rootlibexecdir, 
           install : true,                 
           install_dir : rootlibexecdir)   
```

That seems wrong.
