### ISSUE TITLE
systemd-220 fails to build even using --disable-audit

### ISSUE THREAD

**Issue by vincent-olivert-riera** [systemd/systemd#284]
Even using the "--disable-audit" option in the configure, the build fails with errors like these:

In file included from src/journal/audit-type.c:31:0:
src/journal/audit_type-to-name.h: In function 'audit_type_to_string':
src/journal/audit_type-to-name.h:23:14: error: 'AUDIT_USER_AUTH' undeclared (first use in this function)
         case AUDIT_USER_AUTH: return "USER_AUTH";

Perhaps some code needs to be ifdefed with "HAVE_AUDIT"?

**Comment by poettering** [comment]
hmm, that's weird. did you change your configuration after untarring the tarbal and still have pre-built audit type list files around or so? the src/journal/audit_type-to-name.h file is normally based on the definitions you have, and hence what is in there should also be declared.

The code was a bit broken though, which i fixed in PR #285, but I doubt that fixes your problem.

**Comment by mbiebl** [comment]
Isn't this
http://lists.freedesktop.org/archives/systemd-devel/2015-May/032148.html

2015-06-18 13:47 GMT+02:00 Lennart Poettering notifications@github.com:

> hmm, that's weird. did you change your configuration after untarring the
> tarbal and still have pre-built audit type list files around or so? the
> src/journal/audit_type-to-name.h file is normally based on the definitions
> you have, and hence what is in there should also be declared.
> 
> The code was a bit broken though, which i fixed in PR #285
> https://github.com/systemd/systemd/pull/285, but I doubt that fixes
> your problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/systemd/systemd/issues/284#issuecomment-113127918.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by vincent-olivert-riera** [comment]
Yes, that's it!

**Comment by poettering** [comment]
Closing then.

**Comment by vincent-olivert-riera** [comment]
Which commit fixes the problem?

**Comment by floppym** [comment]
@vriera it's mentioned in the second reply on that thread: ee3c31bf69746c5afc764c3d0337feec1bf25f0e

**Comment by vincent-olivert-riera** [comment]
I already tried that patch and it didn't fix the problem, that's why I asked.

**Comment by floppym** [comment]
That patch affects the files included in the source tarball; if you apply it on top of sources extracted from a source tarball, it will have no effect.

Try removing the relevant files or running make clean.
