### PR TITLE
string-util: fix build error on aarch64

### LINKED ISSUE #19543: Build error on fedora-rawhide-aarch64
See packit failure in #19542 (https://copr-be.cloud.fedoraproject.org/results/packit/systemd-systemd-19542/fedora-rawhide-aarch64/02173219-systemd/builder-live.log.gz).
```
In file included from ../src/basic/af-list.h:6,
                 from ../src/basic/af-list.c:7:
../src/basic/string-util.h: In function â€˜char_is_ccâ€™:
../src/basic/string-util.h:133:19: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  133 |         return (p >= 0 && p < ' ') || p == 127;
      |                   ^~
cc1: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by yuwata**
This fixes the following error:
```
In file included from ../src/basic/af-list.h:6,
                 from ../src/basic/af-list.c:7:
../src/basic/string-util.h: In function 'char_is_cc':
../src/basic/string-util.h:133:19: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  133 |         return (p >= 0 && p < ' ') || p == 127;
      |                   ^~
cc1: all warnings being treated as errors
```

Fixes #19543.

### CODE REVIEW

File: src/basic/string-util.h [hunk 1]
```diff
@@ -130,7 +130,7 @@ static inline bool _pure_ in_charset(const char *s, const char* charset) {
 }
 
 static inline bool char_is_cc(char p) {
-        return (p >= 0 && p < ' ') || p == 127;
+        return (uint8_t) p < ' ' || p == 127;
```
Comment (poettering) [inline src/basic/string-util.h:133]: it might make sense to cast both the lhs *and* the rhs of the `<` comparison. i mean, according to the C standard comparing an unsigned with a signed variable means both are cast to unsigned, so this fix works correctly, but it takes quite some knowledge of C to know that these are the rules. (I had to look it up)
